### ISSUE TITLE
No way to jump to the end of scan reports for blind screen readers 

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#100]
Since results from a scan are dynamically populated, blind screen reader users have trouble jumping to the end of the scan results.

**Comment by bbertucc** [comment]
Perhaps this can be solved with a link at the top of the dom for screen readers?

**Comment by NicolaSaunders** [comment]
Hi - have you considered placing pagination both before and after the table? This would be helpful for both sighted and non-sighted users (saves having to scroll to the bottom to navigate between pages).

If you do this, you should change the aria-label of the second instance of the pagination to make it clear that it's a repeat of the first instance.

**Comment by bbertucc** [comment]
@NicolaSaunders - By "table," are you talking about the table of alerts? Or the black information area on the "Scan" page?

**Comment by NicolaSaunders** [comment]
I was talking about the table of alerts - apologies if I have misunderstood which screen is the concern for users.

**Comment by bbertucc** [comment]
No prob @NicolaSaunders! I think your suggestion is an excellent point for discussion. I suggest opening another issue to discuss it.

**Comment by Cbturtle2** [comment]
> Perhaps this can be solved with a link at the top of the dom for screen readers?

Would this be a button that says "Jump to bottom" or something similar? Interested in taking on this ticket but want to ensure I understand exactly what is needed.

**Comment by bbertucc** [comment]
> Would this be a button that says "Jump to bottom" or something similar? Interested in taking on this ticket but want to ensure I understand exactly what is needed.

 @Cbturtle2 - it may be, but I'm not a screen reader user.

@zersiax, who is a screen reader user, is going to take a look at it. perhaps he can provide better specs to build on?

**Comment by bbertucc** [comment]
@zersiax - Kevin Andrews told me that this wasn't really a bug, but an enhancement request. He could use the quick key to navigate to the bottom, but thought we should add more guided navigation. I'm going to close this issue. Feel free to bill me for your time and add any other comments we should consider.
