### ISSUE TITLE
Code Grammar and Spelling Errors

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#102]
Proper grammar and spelling make the Equalify code more readable. Unfortunately, I am plagued with dyslexia and many grammar/spelling errors slip into the `main` branch. 

For [Hacktoberfest](https://hacktoberfest.com/), I invite anyone to read through `main` branch grammar and spelling. Create Pull Requests for any batch of errors you find.

**Comment by theadeyemiolayinka** [comment]
Hey @bbertucc ,
Howdy?, I would love to be assigned to help rectify the spelling errors.
Thanks man.

**Comment by bbertucc** [comment]
> I would love to be assigned to help rectify the spelling errors. Thanks man.

@theadeyemiolayinka - Looks like @huyszn jumped on it. Do you want to review that PR (https://github.com/bbertucc/equalify/pull/103) and make any fixes?

**Comment by theadeyemiolayinka** [comment]
@bbertucc
Sure, I would. Thanks.
I'm so sorry, I was busy with school work.

**Comment by bbertucc** [comment]
Merged with [mvp-4](https://github.com/bbertucc/equalify/tree/mvp-4). Ready to merge into `main` as soon as testing is complete.
