### ISSUE TITLE
Document/blog about how Equalify can be used as part of a development process

### ISSUE THREAD

**Issue by kreynen** [bbertucc/equalify#109]
Using Equalify to generate a score for live, launched sites is something most people grasp pretty easily and is probably the most common use case. 

This was discussed in https://github.com/bbertucc/equalify/issues/104, but I wanted to call it out independent of the Pantheon-specific visual regression testing.

We haven't done this, but https://gitlab.com/universityofcolorado/uis/webapps/cu-starterkit-project/-/issues/4 describes our plans to add Google Core Vital/Lighthouse testing to our development process instead of manual testing after features are merged into master and deployed.  

With both accessibility and performance, the ideal process catches these issues BEFORE they are deployed, but in many organizations just standardizing the process for checking launched sites would be a HUGE improvement.

**Comment by bbertucc** [comment]
Closing this issue, since our repos docs aren't designed for use case info. However, I am collecting use cases around Equalify to add to https://equallify.app
