### ISSUE TITLE
I would like to be able to add a Backdrop CMS website

### ISSUE THREAD

**Issue by jenlampton** [bbertucc/equalify#110]
Under "Integrations" I see that Drupal is coming soon. Would it be possible to add backdrop cms also?  I expect it could use the same configuration as Drupal.

**Comment by bbertucc** [comment]
Definitely @jenlampton! The "coming soon" integrations are a placeholders for dreams. Do you have any wild ideas for backdrop-specific functions? I imagine we can development enhancements like #89 with a Backdrop module that ran Equalify locally. We could also push updated sites to Equalify, so we didn't have to run the across every page in the XML site map. 

The more specific imagined features are the more likely we'll build them.

**Comment by bbertucc** [comment]
@jenlampton - Could you add a version of the backdrop logo that works over white backgrounds? I can add a "teaser integration" to our integrations page.

**Comment by bbertucc** [comment]
Closing this for now, @jenlampton - But I would love to open it soon! We would need a bit of info on how Equalify could ping a Backdrop site for its page URLs. For instance, we ping WordPress sites via each site's WP API. 

Hope we can re-open soon! Lots of great universities we work with use Backdrop.
