### ISSUE TITLE
Allow sites with more than 1,111 pages to be scanned.

### ISSUE THREAD

**Issue by jenlampton** [bbertucc/equalify#112]
It would be nice if a scan could be completed in batches, so large-ish sites could also participate. 1,111 pages is nothing for a Drupal or Backdrop CMS website, and we need equalify too! (I would argue that large sites need this service even more than tiny sites, where people can realistically scan all pages manually.)

**Comment by bbertucc** [comment]
Thanks @jenlampton! I'll add your note to #73 and close this issue. The limit will be upped next release.
