### ISSUE TITLE
Client readable reports - Evolving from "The Wall of Errors"

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#127]
Gen Herres notes that CEO-ready reports are essential to prove work on accessibility. Charts are key.

**Comment by bbertucc** [comment]
After Gen reported a need for this, a CEO literally told me he needed this. I imagine we would just need to create a public URL of report. There wouldn't be editable filters for the public URL.

**Comment by mgifford** [comment]
Useful metrics to include wiithin this:
- Some grade (errors/page)
- historical chart of errors over time (critical/serious/moderate/minor/grade) would be useful
- Listing of the top 100 critical errors (removing duplication) - that haven't been marked to be ignored

Most folks just want to know are we reducing our risk over time. 

It is also useful to be able to compare multiple departments and know that engineering needs more work on accessibility than the arts department (or whatever).

**Comment by bbertucc** [comment]
Adding a screenshot @mgifford built with Purple Hats. Additional options to export as CSV and PDF.
<img width="1142" alt="Screenshot 2022-12-22 at 4 31 36 PM" src="https://user-images.githubusercontent.com/46652/209236695-82551905-5bb8-4b8c-9e62-37b04c57de99.png">

**Comment by mgifford** [comment]
Just for clarity, that screenshot in the comment above from CivicActions' version of Purple Hats.

The latest version of the report from Singapore Digital Services still looks like this:
<img width="1058" alt="Screenshot from Singapore Digital Services" src="https://user-images.githubusercontent.com/116832/209356830-be6a5826-203b-41a3-8f50-87e480676394.png">

Still useful, but much simpler.

**Comment by bbertucc** [comment]
> Just for clarity, that screenshot in the comment above from CivicActions' version of Purple Hats.

Thanks @mgifford! I can see how the grade helps. Tagging #76 on here, where we talk about some sort of grade or score.

**Comment by bbertucc** [comment]
Maybe we have multiple layout options when creating a report?
<img width="960" alt="Screenshot with a Layouts dropdown that includes a graded view and alert list option " src="https://user-images.githubusercontent.com/46652/227005404-49df1ef7-3478-475d-b4d0-ab2b41bcc056.png">

**Comment by bbertucc** [comment]
We probably want also to list the tests passed. @mgifford noted:

>  the number of passed tests can tell us something about the complexity of a site. If we know that there are 400 passed test & only 1 error, we probably can be more confident about their accessibility than say a page that just has 200 passed tests and the same error. The number of right answers is actually an indication of the work done.

I know OCR particularly appreciates references to work done.

Acrobat publishes tests passed in their report:
<img width="787" alt="A table listing various PDF accessibility tests and passed or failed status" src="https://user-images.githubusercontent.com/46652/227270165-d28461ea-e855-4dd9-9110-30aa6710208b.png">

**Comment by bbertucc** [comment]
Another important point from @mgifford:
>  these tests won't tell you if a document is accessible. It will tell you if a document isn't accessible.

How can we clearly articulate this?

**Comment by bbertucc** [comment]
Another +1 for this is to provide a more interesting screenshot for presentations - the "wall of errors" we currently have isn't very .. err.. visually interesting..

**Comment by bbertucc** [comment]
When completing this we should probably create a `register_report_template()` function so that other integrations could extend templates. 

I would also suggest adopting any new templates as an integration before we work them into core code. That way we can see if people are truly interested by the template before it hits core.

**Comment by mgifford** [comment]
The most interesting about reporting the "passed" tests is that you can begin to aggregate how complex the code is that is being used to deliver the site. This is something that can cut two ways, both:

*   This really complicated HTML/CSS/JS page only has 2 minor errors, hurray! 
*   Why is this simple concept delivered with such a complex set of HTML/CSS/JS? 

Frankly, both are important.  Knowing that a 100 page site has 100,000 testable elements, vs another 100 page site that has a million will matter.  
  
Maybe that complexity is needed. Likely it isn't. The same approach to counting axe bugs could be applied to other web elements.

**Comment by bbertucc** [comment]
Closing this issue in favor of #204, which includes lessons from this ticket and provides a more concise description of the issue.
