### ISSUE TITLE
Crawler indexes different site after 301 redirect

### ISSUE THREAD

**Issue by john-Graham** [bbertucc/equalify#128]
When crawling a site when the crawler hits a URL with a 301 Status that directs do a different domain it will scan the page on the new domain and index it as if it were part of the original site.

An example URL:
https://engineering.wisc.edu/departments/interpro/

gives a status of 301, yet the crawler continues and indexes the initial page it was redirected to. 
https://interpro.wisc.edu/

Suggested behavior is if met with a redirect that goes to a different domain name the crawler moves onto the next page.

**Comment by bbertucc** [comment]
Great catch! Tagging this for the next release.
