### ISSUE TITLE
Exclusions based on CSS Selectors

### ISSUE THREAD

**Issue by john-Graham** [bbertucc/equalify#129]
For sites that are template driven, and use custom Gutenberg blocks It would be nice to create some global trusted exclusions.

We have a block used throughout the site being flagged as low contrast however it is fine.  because it's template-driven adding a css selector exclusion would be nice. 

For example
.acf-block-card h2.section-title 

instances of that h2 will be auto-ignored.

**Comment by bbertucc** [comment]
> It would be nice to create some global trusted exclusions.

Yes! Definitely! +1 to this. I have a grant application out that is for just this. Even if they Microsoft doesn't accept the grant, I might jump on this in the new year or I'm also happy to help anyone build and design the feature.

**Comment by bbertucc** [comment]
Equalify is focusing on issue management (see #198) vs scanning. This issue should therefore be dealt with by a third-party scanning service, like https://github.com/dequelabs/axe-core/. You can also check out an experimental scanning service that we are building: https://github.com/EqualifyApp/scan
