### ISSUE TITLE
Scan not completing

### ISSUE THREAD

**Issue by NicolaSaunders** [bbertucc/equalify#132]
I've tried scanning a new site [www.cinuk.org](https://www.cinuk.org/page-sitemap.xml) 

While the scan is running, the following line appears multiple times: `>>> Unknown column 'tags' in 'field list'`

It ends with this:

```
> Processing alerts...

|=========================================|
|               SCAN STOPPED              |
|=========================================|

Unknown column 'queued_alerts.tags' in 'field list'
```

And when I visit the Sites tab, the new site is showing as unscanned.

**Comment by bbertucc** [comment]
Looking into this. Thanks!

**Comment by bbertucc** [comment]
@NicolaSaunders are you using a local version or the version at https://service.equalify.app/?

**Comment by NicolaSaunders** [comment]
I'm using the version at the version at https://service.equalify.app/

**Comment by bbertucc** [comment]
> I'm using the version at https://service.equalify.app/

Gotcha. And when you clicked "Add Site" did you select "WordPress Site", "Site via XML Sitemap", or "Single Page"?

**Comment by NicolaSaunders** [comment]
Site via XML Sitemap. Here's the URL: https://www.cinuk.org/page-sitemap.xml

**Comment by bbertucc** [comment]
Hey @NicolaSaunders - Everything should be working now. 

I went ahead and scanned the site. You should see 23 alerts when you login again.

Closing this issue, but feel free to open it if any related issues show up.
