### ISSUE TITLE
Monitoring changes

### ISSUE THREAD

**Issue by joelhsmith** [bbertucc/equalify#151]
Comparing the accessibility score from one run to the next would be a (hopefully) low-effort way to generate an alert. It already exists in the JSON file.

```
      "id": "accessibility",
      "score": 0.98
```

Admittedly, the accessibility score does not take into account issues such as contrast ratio instances going from 10 to 12.  We could count if there has been an increase in contrast ratio nodes in the JSON file.

A paid version could:
- Tell exactly which category generated an additional node.
- Generate email notifications #68

**Comment by bbertucc** [comment]
This is related to #76.

I'm going to close this issue for now, but I expect the issue to popup again as soon as we have a solid scoring system.
