### ISSUE TITLE
Sharing a report publicly

### ISSUE THREAD

**Issue by joelhsmith** [bbertucc/equalify#152]
Could the administrator have the ability to share individual Reports publicly (no login) with an obfuscated url? This will allow people to collaborate without needing multiple logins #86 .  The institutional requirement of SSO is sidestepped for some non-sensitive use cases until #86 could happen.

**Comment by bbertucc** [comment]
Yes 100%. This is gaining interest in #127. Closing this issue in favor of that. Hope to get dev on this going sooner than later.
