### ISSUE TITLE
Add Sites Via Spreadsheet (CSV)

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#158]
One user, for instance, wanted to upload a CSV from a domain discovery audit of 2000+ sites.

**Comment by bbertucc** [comment]
This can be another "adder," similar to the XML adder.

**Comment by mgifford** [comment]
Is this a CSV of domains or a CSV or pages in a site? Both are useful.

**Comment by bbertucc** [comment]
Equalify is focusing on issue management (see #198) vs scanning. This issue should therefore be dealt with by a third-party scanning service, like https://github.com/dequelabs/axe-core/. You can also check out an experimental scanning service that we are building: https://github.com/EqualifyApp/scan
