### ISSUE TITLE
Elevate "more info" to be displayed in the report (not behind a button)

### ISSUE THREAD

**Issue by maggiewachs** [bbertucc/equalify#167]
I'll give an example: in my latest scan, the issue of duplicate IDs was discovered. I'd like to be able to see the problematic markup displayed in the row so that I can scan quickly to see if the same markup is causing a problem in multiple pages (often the case when using templates). This would _really_ help when capturing this information for developers in Jira, github, etc.

**Comment by bbertucc** [comment]
Thanks @maggiewachs! Have you used a service or seen a report that lists the issue in a way you imagine? Visual examples like screenshots would be super helpful. Thanks again!
 Linking this issue to #166 and #127.

**Comment by maggiewachs** [comment]
@bbertucc actually the screen grab you have on the Equalify home page would be perfect -- maybe with the HTML in its own column so it could be sorted:
![image](https://user-images.githubusercontent.com/228885/212926290-bbb5ab12-acf7-40fb-82b6-e6bff64137b5.png)

**Comment by maggiewachs** [comment]
@bbertucc also, is there a way to download the results, maybe as a CSV? If not, that would be super useful, too.

**Comment by bbertucc** [comment]
@maggiewachs-
Re: exporting results.. Could you talk a bit about how you use the exports on a related issue I created? Exports, surprisingly, haven't been requested before.. See https://github.com/bbertucc/equalify/issues/170

Your feedback can make this feature a reality!

**Comment by bbertucc** [comment]
Closing this issue in favor of https://github.com/bbertucc/equalify/issues/204, which includes lessons from this ticket and provides a more concise description of the issue.
