### ISSUE TITLE
axe-core cannot reach the page.

### ISSUE THREAD

**Issue by mgifford** [bbertucc/equalify#172]
I recently got this error “axe-core cannot reach the page.”

<img width="882" alt="Screenshot of the Reports page & the error message above" src="https://user-images.githubusercontent.com/116832/213557766-313678c1-c6c6-463b-bd71-1cf2e30830cc.png">

**Comment by bbertucc** [comment]
Thanks @mgifford! Already fixed it on [service.equalify.app ](https://service.equalify.app) with #173, which will be merged into [Beta-1](https://github.com/bbertucc/equalify/milestone/6).
