### ISSUE TITLE
Priority Support?

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#177]
Triaging support has been a challenge for me. Perhaps I should create a "priority support" product? For $x/mo, folks would get access to chat support with guaranteed response time. I love the idea of support because it keeps Equalify free.

I would be curious if anyone would pay for support like this? And how much would they pay? I would probably want 4-5 folks to opt in before I start guaranteeing response time.

**Comment by mgifford** [comment]
People might want to pay for help to get started.  They might want to pay to have bulk actions done on certain kinds of errors.  

I think most folks who would sign up would be unsure why they need support? Is Equalify extra complicated? What would I need support to do? Is the free support slow? 

The first thing you want to do is sell them on the service. Right now they don't know that they need Equalify. 

Maybe the free tier with 2000 searches is enough for many people.  

Maybe they have questions about how to address the issues.  

Just gotta be clear what support you're going to be able to offer and what client need it is satisfying.

**Comment by bbertucc** [comment]
Those are great points @mgifford! 

Focusing on products that push the features of Equalify would allow me to focus on marketing what Equalify is. The paid products could include support as an additional perk, if necessary.

**Comment by mgifford** [comment]
You have to feel out what folks are willing to pay for. Where they see value in what you've done. And what needs your competition hasn't been able to satisfy.

**Comment by bbertucc** [comment]
Great points! Closing this issue in favor of #133 - will re-open it when someone says they'll pay for support
