### ISSUE TITLE
What organization should Equalify belong to?

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#184]
@mgifford pointed out that Equalify should probably be housed in an organization. An organization can make the platform seem more professional, helping with sales - especially for enterprise customers.

I am open to starting an "Equalify" organization, but I'm also an owner of two orgs:
- [Decubing](https://decubing.com/), a web development agency
- (Philosophers](https://philosophers.notion.site/), a group of philosophers

Adding another org would further complicate things like taxes and emails. That said, if I added Equalify to Decubing, would I scare off potential agency users? Is Philosophers to esoteric? What else should I consider?

I hope to resolve this issue on completion of the ["I Heart Emoji Accessibility" ](https://github.com/bbertucc/equalify/milestone/6) sprint.

**Comment by bbertucc** [comment]
Related: https://github.com/bbertucc/wcat/issues/2

Whatever is decided there could become the resolution to this issue.

**Comment by mgifford** [comment]
There is starting an organization. Then there is starting a GitHub organization.  I was mostly suggesting that this lie under a GitHub organization. That should have no tax impact, but would affect how this project is percieved. 

Until the money coming in from Equalify is causing problems for Decubing, I'd keep it there.  It's just a project of your web development agency (essentially).  

It can always move later.

**Comment by bbertucc** [comment]
Ah, yes @mgifford - I see what you mean. I also see opportunities to build a new org, since very little of my time is actually spent with Decubing ATM.

Will consider "Decubing" a fallback. Aiming to put this issue to bed on our next release, the `beta-1` release.

**Comment by bbertucc** [comment]
@TheBoatyMcBoatFace created https://github.com/equalifyapp - perhaps that's the org we use?

**Comment by bbertucc** [comment]
The first draft of this business plan works to resolve this issue: https://github.com/EqualifyApp/handbook/blob/business/Business.md .. Please add any feedback!

**Comment by bbertucc** [comment]
Closing this issue, since business will dictate the resolution rather than community input.
