### ISSUE TITLE
">>> Data too long for column 'more_info' at row 2"

### ISSUE THREAD

**Issue by dylanhthomas** [bbertucc/equalify#189]
I received a clean scan after this error. Using axe-core cli, 32 errors were found.

Equalify output:
![image](https://user-images.githubusercontent.com/824168/217901098-1aaa86fe-95c8-4d1e-a268-f2cb88fb6542.png)

axe cli output:
![image](https://user-images.githubusercontent.com/824168/217901245-c49f4fbf-596f-443b-8eae-e4d00780acd5.png)

**Comment by bbertucc** [comment]
The next version https://github.com/bbertucc/equalify/tree/beta-1-rc1 fixes this issue. Closing it for now.
