### ISSUE TITLE
Add option to configure stand alone WAVE api instance

### ISSUE THREAD

**Issue by kreynen** [bbertucc/equalify#213]
Equalify assumes that WAVE will be run at wave.webaim.org in functions like https://github.com/bbertucc/equalify/blob/main/integrations/wave/functions.php#L111C25-L111C40

Because WAVE is also available as https://wave.webaim.org/standalone, it would make sense to add a default baseurl to https://github.com/bbertucc/equalify/blob/main/sample-config.php#L23 that can be changed to use the sand alone API. 

The standalone API does not include reports. It's only generating JSON and screenshots. Additional work will be required to fully integrate with the standalone API, but adding this initial configuration will allow us to leverage Equalify to parse the sitemap.xml files of sites and generate the JSON version of the reports.

**Comment by bbertucc** [comment]
I would like to see this issue completed for our next version. 

FYI- We will be pulling integrations out of Equalify's core codebase, so issues like this will eventually live outside the repo.

**Comment by bbertucc** [comment]
Related to #216

**Comment by bbertucc** [comment]
This issue was moved to a separate WAVE repo to satisfy #223 .

Here is the new location of the issue: https://github.com/bbertucc/equalify-wave/issues/1
