### ISSUE TITLE
Add option to only scan URLs in sitemap.xml that report changes since last scan (Last Modification Date > scanned timestamp)

### ISSUE THREAD

**Issue by kreynen** [bbertucc/equalify#214]
The current Sitemap XML integration assumes that all URLs should be scanned every time.

The XML might contain hundreds or thousands of URLs, but https://github.com/bbertucc/equalify/blob/main/helpers/process_sites.php#L41 returns a single URL of the sitemap.xml the same way it returns a single URL property type. That URL is then processed by [xml_site_adder()](https://github.com/bbertucc/equalify/blob/main/models/adders.php#L103). The function tries to take all URLs returned by the XML, convert that to JSON and pass all those URLs as pages to be scanned in https://github.com/bbertucc/equalify/blob/main/helpers/process_sites.php#L123. If the total number of URLs in the sitemap.xml exceeds the $GLOBALS['page_limit'], none of the pages will ever be scanned.

In https://github.com/bbertucc/equalify/blob/main/cli/scan.php#L67, the timestamp of the last successful scan of that site/property is saved. While it's possible that changes to a site's theme or blocks that wouldn't be reflected in the Last Modification Date in the sitemap.xml could introduce an accessibility issue, in some use cases the application (in our case, a specific Drupal configuration) and the content of each site using that application will be tested independently. The Drupal application is first tested with demo content we know isn't introducing accessibility issues. This makes it less likely we are introducing issues to the sites using that application and any issues identified in the URLs of the sitemap.xml are content-level issues.

**Comment by bbertucc** [comment]
Adding the Beta 1 Milestone to flag this issue. We'll need to migrate this issue into a WAVE-specific repo when we launch the next Equalify version.

**Comment by bbertucc** [comment]
Related to #216

**Comment by bbertucc** [comment]
Closing this issue. I haven't heard from others that this was necessary. Also, with the next release, scan processes like this will be handled by integrations and not the core Equalify system.
