### ISSUE TITLE
Pay Devs to Build Equalify

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#217]
## Overview
Contributing to open-source projects like Equalify sometimes requires cash incentive. That's why I'm making funds available to make Equalify better. All your contributions will be licensed under AGPL Version 3.

## Qualifications
- Proven experience working with PHP and JavaScript.
- Firm grasp of the [Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/TR/WCAG22/).
- Familiarity with popular platforms and frameworks such as WordPress, Drupal, React, and Vue is a big plus.
- Interest in working in the open.  All contributions are public. 
- An understanding and appreciation for the value of open-source technology and website accessibility.

## Compensation
Some devs want to work hourly. Others ask for a flat fee to accomplish tasks. We can talk through compensation.

Note: Proficiency in haggling is not a qualification for this role. I'm hoping to work with devs who are passionate about open-source accessibility first and foremost. It should feel good to do this work. Getting paid is a bonus. 

## How to Apply
If you're passionate about making the web a more inclusive place and have the required skills, I'd love to hear from you! 

1. Checkout our [issues tab](https://github.com/bbertucc/equalify/issues) and codebase ([beta-1-rc-1 ](https://github.com/bbertucc/equalify/tree/beta-1-rc1) has the most recent updates).
2. Send me an email <[blake@decubing.com](mailto:blake@decubing.com)> with some details about your background and what you can do to make Equalify better - your work doesn't have to be solving an existing issue.
3. If you seem like you're genuinely interested in working on the project and you have experience that proves your skills, I'll invite you to meet with me to further discuss the opportunity and we'll take it from there.

I am committed to creating an inclusive environment for everyone who works with us. I encourage applicants with diverse backgrounds, disabilities, and experiences to apply. For more info on my thinking around inclusion, check out my exchange with [this Drupal Slack thread](https://drupal.slack.com/archives/C27JQ4YNB/p1692045755337739).

 ## Additional Information
- I will not respond to headhunters or agencies. You should only contact me if you are the developer that Equalify would be paying and working with.
- Bonus points are always given to devs that have contributed to the codebase (shoutout to @szepeviktor with PR 218!) Prior contributions to Equalify are not required, but it is something I notice.
- Feel free to comment on this issue or email me if you have any questions.

**Comment by bbertucc** [comment]
Someone asked on [Drupal's Slack](https://drupal.slack.com/archives/C27JQ4YNB/p1692047372573059?thread_ts=1692045755.337739&cid=C27JQ4YNB) about the relatively low compensation.

The compensation rate is intentionally set to cover the basic needs of a developer who wants to work on an open-source project that has social benefits. Any compensation I've given to myself or others has followed that basic premise, and I believe the right person will be attracted by more than just the relatively low salary.

That's not to say compensation won't grow. I'm just focused more on making a great product than making money right now.

**Comment by bbertucc** [comment]
Posted a bit more information behind the thinking of this position on Twitter (look at replies in thread): https://twitter.com/bbertucc/status/1691847865247694929?s=20

**Comment by bbertucc** [comment]
More conversation happening in these threads:
- https://highedweb.slack.com/archives/CDBQCTV2B/p1692286896605339
- https://nola.slack.com/archives/C06891X0W/p1692286808782289
- https://web-a11y.slack.com/archives/C069AKEAJ/p1692286826712309
- https://poststatus.slack.com/archives/C028LBV5ZBQ/p1692286816567129
- https://wordcampus.slack.com/archives/C0C3VUV28/p1692286908489479
- https://drupal.slack.com/archives/C27JQ4YNB/p1692045755337739

I encourage anyone who reaches out to me to read them. (If you cannot access the threads let me know.)

**Comment by szepeviktor** [comment]
@bbertucc I'd like to work on this team for free for the first year.
I am not a developer but I am able to extremely deeply [care about](https://github.com/szepeviktor) live web applications and open-source projects.
A few become viktor fans, others will ask me _"What's the value?"_ and furiously send me packing.

**Comment by bbertucc** [comment]
> @bbertucc I'd like to work on this team for free for the first year.

Okay, @szepeviktor - on those terms, you're hired! I'll still keep this issue open and hope that lots of people apply for the job. The more developers we have working on Equalify, the quicker we can make the internet accessible.

Your first issue: https://github.com/bbertucc/equalify/issues/219 (anyone can also jump on that issue).

**Comment by bbertucc** [comment]
I updated this issue from a part-time position to a fund after hearing feedback from lots of devs. (Thank you all!) That doesn't mean I won't offer a salaried position to a dev. I very much hope paid contribution leads to meeting the right dev to work with. I encourage anyone interested in salaried work to apply for this opportunity.

**Comment by bbertucc** [comment]
Closing this ticket because I think we have a pretty good team of folks to build the initial version. Anyone can still be sponsored. Just follow those steps listed, but I won't be advertising this as much anymore.
