### ISSUE TITLE
Test Beta-1-RC1

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#219]
## What is the issue?
@ebertucc coded a great release candidate for Equalify's next version: https://github.com/bbertucc/equalify/tree/beta-1-rc1

We need testers!

To test:

1. Pull down the branch and install according to the installation instructions in [the branch's readme.md](https://github.com/bbertucc/equalify/tree/beta-1-rc1#readme).
2. Add a bug to [this repo's issues](https://github.com/bbertucc/equalify/issues) whenever you encounter an issue that has the development branch `beta-1-rc1`.

## What will resolve this issue?
When all the issues related to `beta-1-rc1` are resolved, this issue can be closed.

**Comment by szepeviktor** [comment]
https://github.com/bbertucc/equalify/blob/069c72a61136444cb8792f6f08bd31e09fece683/sample-config.php#L23-L24

Could it be that axe-equalify was deleted?

**Comment by bbertucc** [comment]
> Could it be that axe-equalify was deleted?

Good catch @szepeviktor! The repo URL changed to this: https://github.com/bbertucc/equalify-automated_scan

**Comment by szepeviktor** [comment]
All right.
Setting up my environment ... 🏃🏻‍♂️

**Comment by bbertucc** [comment]
Test closed! Now we're moving to RC-2...
