### ISSUE TITLE
Invalid URL invalidation

### ISSUE THREAD

**Issue by ebertucc** [bbertucc/equalify#22]
Using just a second-level and top-level domain (e.g. graceblake.com) throws an exception. PHP's `FILTER_VALIDATE_URL` filter doesn't consider it a URL.

This isn't a great user experience, but may not be a bug if you want to force the protocol to be specified.

![image](https://user-images.githubusercontent.com/8377738/163894734-035a9875-7bf0-4888-bf5d-dbf9c2f39e5c.png)

**Comment by bbertucc** [comment]
@ebertucc what was your expected behavior?

**Comment by ebertucc** [comment]
I expected it to add the site. Browsers and cURL both work with `somesite.tld`-style URLs. See [this thread](https://curl.se/mail/lib-2020-07/0038.html) for more of the cURL perspective on URL validation.

**Comment by bbertucc** [comment]
Thanks you @ebertucc.

I committed the updated.

You can grab the latest version of the [MVP Alpha release ](https://github.com/bbertucc/equalify/releases/tag/mvp-1-alpha-2).

Does that realize all your cURL fantasies?

**Comment by ebertucc** [comment]
Yep, thanks! Removing sanitization/validation at input time does open the door to SQL vulnerabilities, though.[ I still think it's worth doing](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html), just not using that built-in method. I particularly like the idea of having a normalized/canonical form for URLs the app would accept. I've seen nasty regular expressions floating around the internet that might be good for this.

On that same note (and this should really be a separate issue) [mysqli's docs](https://www.php.net/manual/en/mysqli.query.php) recommend parametrized prepared statements instead of `query` when there's variable input, a sentiment shared by [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html).

**Comment by bbertucc** [comment]
Yep. Not including parametrized statements is def. a bug. Another person caught that: #25 

Closing this issue for now, since the expected behavior is now as expected.

Will pick up on added validation as needed.

**Comment by bbertucc** [comment]
Yep. Not including parametrized statements is def. a bug. Another person caught that: #25 

Closing this issue for now, since the expected behavior is now as expected.

Will pick up on added validation as needed.
