### ISSUE TITLE
Various Core Upgrades

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#224]
## Overview

@TolstoyDotCom reported a bunch of updates to think about. I imagine we'll need to create lots of separate tickets to tackle these challenges. For now, I'll open this ticket to respond to the items listed here:

- [ ] First, move all classes into namespaces and autoload them.
- [ ] Use Symfony components to replace some of the functionality. Those are standalone and don't require the whole Symfony codebase. Since you're already using Composer this seems like it wouldn't be a big leap.
- [x] Replace hooks.php with Symfony's EventDispatcher.
- [ ] Replace code that builds forms with Symfony's Form, https://formr.github.io/ , or https://github.com/oscarotero/form-manager
- [ ] The first two add nonces to forms, providing a little extra security.
- [ ] Use Symfony's Console to deal with the CLI.
- [ ] Use Symfony's HttpFoundation in place of accessing $_GET etc directly.
- [ ] *Hopefully* use Symfony's DependencyInjection (and YAML config files) to load services.
- [ ] In lieu of authentication, create a page with a long random name (e.g., dsj3445kwekrd35we.php) on installation that the user must visit once every two weeks or so to get a cookie. The CRUD etc functions only work if the user has that cookie.
- [ ] Or, give them a PIN on installation (and keep it unencrypted in the db). When they try a CRUD operation, if a cookie isn't present, there's an additional form field for the PIN. If they enter the correct PIN it sets the cookie and they don't have to enter the PIN for two weeks or so.
- [ ] The user would be encouraged to bookmark that page or write down the PIN.
 - [ ] Add a diagnostic mode. For instance, when it throws an exception if axe_uri is empty, catch the exception at the top level and run a report that reviews the settings. In the case of an empty axe_uri, it would say "axe_uri is empty. You need to go to page ABC, set the value, and save that form. Then, try again."
- [ ] Code blocks should always have curly braces to avoid issues like this https://www.imperialviolet.org/2014/02/22/applebug.html
- [ ] Use [] instead of array(); due to the other features being used in the code there's no worry about running on outdated versions of PHP. This can be done automatically.
- [ ]  `get_integration_fields` and `get_integration_tags` have a huge security flaw. The integrations.php functions need to be put into their own class and sanitization needs to be added.
- [ ] Change DataAccess from a global static class into two instantiated classes that are passed to clients.
- [ ]  The first will just deal with low-level db operations, the other will deal with meta operations. For meta operations, serialization will be transparent.
- [ ]  Move the table definition SQL into config files.
- [ ]  All db operations will go through the low-level class, and that will have full sanitization.
- [ ] Try to move as much HTML as possible out of PHP files and into template files.
- [ ] Use Twig as the templating system. Most of the HTML in the views directory can be copy/pasted, but most variables will have to be prepared first for the templates. E.g., the use of DataAccess in integration_settings.php will be replaced with just printing a variable.
- [ ] Change covert_code_shortcode name, put into class using a template.
- [ ] Create a Pager class implementing IPager, put in Display namespace.
- [ ] Put any Javascript into separate files and load them in the templates.
- [ ] `reports.php` and similar would be split into two files: one that does the preprocessing, and a template.
- [ ] (Perhaps) add a way to translate strings into other languages.
- [ ] The Axe and WAVE functions.php can be converted into classes that implement the same interface. The a11ywatch functions are a superset of that interface; what to be done there is TBD. Instead of building function names, process_integrations would call the interface's methods.
- [ ] Preferably, move the .json and image files in integrations into directories for config files and images respectively.
- [ ] Add an AppDirectories class which can be used to get the image files directory etc.

## Further Notes
A few items we'll need to consider while we continue development on this ticket:
1. **The priority for now is to create a better hook system (#174).** The roadmap should do whatever work needs to be done to do that. Checkout the issue for more information on why that is the priority.
2. **Our core business requires very easy-to-add integrations** - think WordPress plugins - with standard Equalify classes/functions and the ability to hook into other Equalify functions. These classes/functions help integrations safely register tags, define where a URL is sent, define how any returned data is saved to Equalify, and set administrative items like fields where a user can add API information.
3. **We'll be dealing with huge amounts of data.** The typical Equalify user scans 10,000 pages. Those scans return an average of 50 alerts per page. Equalify will have to process all those alerts to see which are resolved and can be marked Equalified. Mentioning this so that any refactoring can meet the very large amount of data that's coming.
4. **We are totally updating our reporting design.** See #204. That issue is going to be tackled in the next release, so we want to make sure we're being smart about what work gets done when. 
5. **Any roadmap will need to include training.** Symfony is new to some of our core contributors (including me). We should probably budget a bit of training.

**Comment by zersiax** [comment]
Another suggestion may be to use an ORM like Doctrine rather than manually defining SQL, this would make altering and maintaining the database easier and less error-prone as it is handled by PHP rather than  SQL directly, and will give you a number of things like data sanitization for free, but it would be a pretty big change. Just my to cents.

**Comment by bbertucc** [comment]
My general questions:
- Why are require authentication before initiating CRUD functions? The platform is designed to be run mostly locally by users who are in control of it.
- Why would you suggest moving HTML out of PHP files and use Twig? I built one version with handlebars, but our HTML was so simple we ended up not needing it.

**Comment by bbertucc** [comment]
@TolstoyDotCom - I created a roadmap of sorts to give you an idea of what I'm trying to do: https://github.com/orgs/EqualifyEverything/projects/2 .. I'm mainly curious how your work can fit in with the requirements I suggested.

**Comment by TolstoyDotCom** [comment]
@bbertucc: someone might accidentally make their installation publicly-accessible, or do it intentionally so others can use it. That might result in a hacker compromising their server or PC or information disclosure of some kind.

One reason to separate HMTL from PHP is because being like Wordpress is generally a bad idea. Plus, it's easier for themers to deal with and it's easier to read. Also, you might at some point want to output to XML, JSON, etc and in that case all you'd need to do is provide a new template.

**Comment by bbertucc** [comment]
> hacker compromising their server or PC or information disclosure of some kind.

Could this just be resolved by adding into the config or README file? We could write something like: "Equalify is designed for local use. If you create a publicly accessible deployment of Equalify, we highly recommend adding authentication to prevent security issues."

Since we have limited resources, I'm trying to focus open-source work on delivering the basic functions of Equalify. Authentication is an add-on via our cloud version and core authentication might complicate that. 

> you might at some point want to output to XML, JSON, etc and in that case all you'd need to do is provide a new template.

Is there any framework/platform that could serve as a model for how we'll structure the templating? I'm trying to wrap my head around how the data model will associate with twig.

**Comment by bbertucc** [comment]
This issue has been approved with @TolstoyDotCom working on it. I've converted the items into tasks, which we can tick off as we commit to core.
