### ISSUE TITLE
Create New Equalify Templates, Removing Existing Views

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#226]
## What problem is the feature trying to solve?
User testing in #204 revealed that the user experience (UX) and way we've created views is more complicated than it needs to be. That issue also identified new features that will be mission-critical to Equalify success. Additionally, #224 pointed out key technical shortcomings that work outside of traditional MVC patterns.

## Desired Solution
Simplify the UX and develop pages.

Equalify's main navigation will now include three links: "All Reports", "Settings", and "My Account". The navigation will be in a header after the "Equalify" logo, which will ink to the All Reports page.

Those pages will each be constructed by different twig templates and controllers that populate template content. 

I've created a description of each template in the following issues:
- #228 
- #229
- #230
- #231
- #232
- #233
- #247

## Technical Notes
- This should be written as a new twig template with content conditions in the controller, following MVC best practices.
- We'll use basic styles from [Bootstrap](http://getbootstrap.com)
- We'll probably have to think about how to deliver data to these views in a way that is efficient. Special considering should be taken in how we deliver data to the report page, described in #232.
- We created a Miro board that wireframes out the different views. Everything in the Miro board should be described in tickets and sub tickets related to templates because we want to be screen-reader first and work with blind users. Here is the link to the Miro board: https://miro.com/app/board/uXjVMX3i1XA=/?share_link_id=156482074960

## Steps to Completion

- [ ] Develop a "dummy" Twig template, using sample data in the controller.
- [ ] Confirm features via User Testing.
- [ ] Make updates from User Testing lessons.
- [ ] Replace sample data with actual features.
- [ ] Integrate page and related features into the core codebase.

**Comment by bbertucc** [comment]
Just added a bunch of stuff to this ticket to start progress. @zersiax and I will be working on this.

**Comment by bbertucc** [comment]
FYI, @zersiax - I've created a branch we can work from: https://github.com/EqualifyEverything/equalify/tree/226-update-equalify-views

I imagine we can just create a temporary folder like `/dumb_twig` that can hold twig work before we hook it up to our backend.

**Comment by jwgoedert** [comment]
![image](https://github.com/EqualifyEverything/equalify/assets/6878159/3e1f1e0f-418c-40ab-960b-f7c37eeba7d7)
@bbertucc 
Fooled around with some nav thoughts yesterday. I don't think we have a ticket/issue for creating the universal header with  --reporting, setting, my account- unless it's on a different branch. Might make sense to have a base Twig template that contains this functionality and extend the additional views from it? In terms of short term dev could do a conditional to hide left nav and show top menu when developing the new UX and templates?

**Comment by bbertucc** [comment]
@jwgoedert - Good point. I added https://github.com/EqualifyEverything/equalify/issues/247

**Comment by bbertucc** [comment]
The latest commit resolves this issue.
