### ISSUE TITLE
Add Alert Editor Page

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#228]
## What problem is the feature trying to solve?
Currently, Equalify only receives alerts from automated tests. That means we can't include manual alerts from user tests.

## Desired Solution
Create a new "Alert Editor" page.

On this page, users would add or edit a manually edited alert. 

Note: Users should not be able to edit alerts that were added through automated tests.

The page would include a form with the following fields:
- Message (Required) - A required field to add a short message for the alert body.
- Property (Required) - A dropdown field with all the properties. A user would select the property the alert is related to. Property names will be queried from the table that's currently properties (formally sites).
- Source URL (Required) - The URL of the page the alert is related to. This should be validated to make sure it's a valid URL.
- Status - Dropdown with Equalified, Active, or Ignored.
- Meta: Code Snippet - The user can add multiple code snippets related to the alert. They can also delete any code snippet.
- Meta: Notes - A text area for additional notes the user may add to the alert.
- Meta: More Info URL - A link to more info. This should be validated to make sure it's a valid URL.
- If you are editing an existing alert, this field's value would be the existing data.

On save, the alert will be either added or updated in the `alerts` table.

If the user is editing an alert, we should also include a button to "Delete" alert. Deleting an alert should prompt a confirmation with a warning before any deletions happen.

## Technical Notes
- This should be written as a new twig template with content conditions in the controller, following MVC best practices.
- We'll use basic styles from [Bootstrap](http://getbootstrap.com)
- Additional information is available on #226.

## Steps to Completion

- [x] Develop a "dummy" Twig template, using sample data in the controller.
- [ ] Confirm features via User Testing.
- [ ] Make updates from User Testing lessons.
- [ ] Replace sample data with actual features.
- [ ] Integrate page and related features into the core codebase.

**Comment by bbertucc** [comment]
This is related to #113

**Comment by jwgoedert** [comment]
Stubbing this out, I don't see _Status_  dropdown in the requirements, but had "Active, Equalified, Ignored" on issue #113. Also wondering about functionality of 'Property' drop down. In the wires it looks as if the user can select multiple properties and have them displayed, is this what we're looking at here or single select?

**Comment by bbertucc** [comment]
> Stubbing this out, I don't see _Status_ dropdown in the requirements, but had "Active, Equalified, Ignored" on issue #113. Also wondering about functionality of 'Property' drop down. In the wires it looks as if the user can select multiple properties and have them displayed, is this what we're looking at here or single select?

Added the status dropdown. You are right about the status items. Alerts can only have on property selected. The property dropdown will list all the properties. It should be a single select.

**Comment by jwgoedert** [comment]
![image](https://github.com/EqualifyEverything/equalify/assets/6878159/c2019b5e-b29b-495d-964d-b3b3dfe2f5d8)
@bbertucc Making some headway with a few styling and functionality challenges remaining. Here's the most up to date view with dummy data coming from the controller. I haven't yet attempted to plug any functionality into the buttons(add/delete for snippets or save/delete for the full form) let me know if you have time for a quick call some time tomorrow or over the weekend. Just want to make sure I'm on the right track-much appreciated! https://github.com/EqualifyEverything/equalify/tree/228-add-alert-editor-template

**Comment by bbertucc** [comment]
@jwgoedert - Looking good. For future reference: we review any work on Monday or Wednesday, but you can always text me for a call when you're blocked by something. You're also welcome to grab time from my calendar: https://cal.com/equalify

**Comment by bbertucc** [comment]
Adding @TolstoyDotCom to get the controller and relevant actions hooked up. The template that @jwgoedert created should be used to either edit or add an alert. See notes for special conditions.

**Comment by jwgoedert** [comment]
@bbertucc Think I solved the issue I was having yesterday by unsetting session variables after adding or updating db. The latest changes are on the "refactor/notice-editor" branch [](https://github.com/EqualifyEverything/equalify/tree/refactor/notice-editor )
I still need to add the toggle for archived and it is currently only pulling first value from code snippets array if multiple are added with meta. Will be back at it early-mid afternoon and let you know if I hit any snags!

**Comment by jwgoedert** [comment]
![image](https://github.com/EqualifyEverything/equalify/assets/6878159/5dd8c7f8-46b1-4f0a-bd1d-f10d98febfa6)
@bbertucc I added the archived boolean with this style of toggle. Let me now if you'd prefer dropdown.

**Comment by jwgoedert** [comment]
This should be all good to go. https://github.com/EqualifyEverything/equalify/tree/refactor/notice-editor  May be edits/some cleanup after you take a look.

**Comment by bbertucc** [comment]
The latest push resolves this issue
