### ISSUE TITLE
Add All Reports Page

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#231]
## What problem is the feature trying to solve?
Currently, reports are added directly to a navigation. This limits the number of reports that can be added. 

## Desired Solution
This view shows all the reports a user has saved. Each report link includes the name of the report and a description of the report if the description is available. Clicking on a report links to the page described in #232.

The view also includes the option to "Create New Report", which links to the page described in #233.

Note: This will be the default page that a user finds when they click on the Equalify logo or login for the first time.

## Technical Notes
- This should be written as a new twig template with content conditions in the controller, following MVC best practices.
- We'll use basic styles from [Bootstrap](http://getbootstrap.com)
- Additional information is available on #226.
- Descriptions and Titles should have a set amount of maximum characters (120) because text can be very long, along with a conditional elipses if descriptions or titles are longer.

## Steps to Completion

- [x] Develop a "dummy" Twig template, using sample data in the controller.
- [x] Replace sample data with actual features.
- [ ] Integrate page and related features into the core codebase.

**Comment by jwgoedert** [comment]
@TolstoyDotCom Hey Chris, Great meeting you today. I have to step away for a few hours but I stubbed out some code for this initial template and pushed up a branch with my changes. 
https://github.com/EqualifyEverything/equalify/tree/231-add-all-reports-page

I will be putting some more time on it tonight so may be better to check out tomorrow just wanted to post the link-may check back with you tomorrow to insure I'm configuring things correctly. Thanks in advance! http://equalify.ddev.site/index.php?view=all_reports#

**Comment by jwgoedert** [comment]
<img width="643" alt="image" src="https://github.com/EqualifyEverything/equalify/assets/6878159/5c4461c3-7bb8-44ba-b060-f570ffa52dd8">
@bbertucc 
Have some initial progress although I had to pivot and hardcode an array as I'm tackling a linkage issue between my dummyData controller and the twig template.  Going to e-mail @TolstoyDotCom Chris to see if I can get some help today or tomorrow. Still tackling styling and other bits but going somewhere. Will comment on #226 about some other questions
Merged _remove_hooks_php_ branch into the _231-add-all-reports-page_ branch.

**Comment by jwgoedert** [comment]
Have structural parts complete on "231-add-all-reports-page" branch. Going through link functionality and accessibility along with text length controls etc. May have some stylistic questions(the text etc. is slightly larger and different than mockup...). Page can be viewed at [equalify.ddev.site/index.php?view=all_reports](url) from local. Will touch back tomorrow with any lingering questions

**Comment by jwgoedert** [comment]
@bbertucc I think this is ready for local user testing. I've included an image. I left the body text and title the bootstrap defaults as that was recommended for visibility. It's a little larger than mockup but think it works. I bolded the title and added text truncation (the last card in this image displays matching and truncating to 120 char limit). I wasn't sure if you wanted any type of card size limiting or uniformity of sizing. Should I reach out to Florian as I get these elements ready or send them your way first?
![image](https://github.com/EqualifyEverything/equalify/assets/6878159/e9a5f700-45f0-451e-97ef-7d91cc03cc4a)

**Comment by bbertucc** [comment]
Removed the user testing development step for this template, since it's such a basic page user testing would be unnecessary. Adding @TolstoyDotCom to take care of replacing dummy data with actual features.

**Comment by jwgoedert** [comment]
Good deal, going to adjust the things we spoke about yesterday and move onto the Header/add alerts

**Comment by bbertucc** [comment]
@TolstoyDotCom - do you need anything to hook up the controller to the DB so it's actually pulling data? looks like everything is here: https://github.com/EqualifyEverything/equalify/blob/231-add-all-reports-page/src/Controller/AllReportsController.php

**Comment by bbertucc** [comment]
With ac596ed15a709860b755917600d26fed372a75e9 this is complete
