### ISSUE TITLE
Update Report Editor Page

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#233]
## What problem is the feature trying to solve?
Building #232 necessitates a new way to edit and add a report.

## Desired Solution
This page includes fields to edit a new report. 

The fields include:

- Report Name: A required text input.
- Report Description: A text area for an optional description.
- Display: A dropdown with the option "Private" or "Public". This option will only appear on the cloud version.
- Properties: A checkbox area with a list of properties.
- Source URLS: Users can add multiple source URLs. Source URLs can be separated by a comma.
- Blocks: The blocks a user wants on the page. They can check any of the blocks listed above.
- Tags: An editable table of tags. This table will include all the tags that are active. Four columns are present: Name (with the tag name), Weight (a user can set the weight to influence the grade), Hidden? (A user can select true/false to hide alerts related to the tag)
- Message Filters: A user can add regular expression code to filter messages.

The fields are populated if a user is editing an existing report. The fields are not populated if the user is creating a new report.

At the bottom of the page, a user can choose to save or delete the report. 

On Save, add or edit an entry in the `reports` table.

On delete, show warning and confirmation. When deleted, the report will be permanently deleted.

## Technical Notes
- This should be written as a new twig template with content conditions in the controller, following MVC best practices.
- We'll use basic styles from [Bootstrap](http://getbootstrap.com)
- Additional information is available on #226.

## Steps to Completion

- [ ] Develop a "dummy" Twig template, using sample data in the controller.
- [ ] Confirm features via User Testing.
- [ ] Make updates from User Testing lessons.
- [ ] Replace sample data with actual features.
- [ ] Integrate page and related features into the core codebase.

**Comment by jwgoedert** [comment]
![image](https://github.com/EqualifyEverything/equalify/assets/6878159/2f1fe48c-2e05-4ce9-86ca-37c30c38b5de)
Have a base down for the Tags Table, implemented a basic search on only the first column but can expand as desired(this is handled with a basic inline js script for if we go the json route, would have to refactor if we're hitting db etc.). Also thought these checkboxes might be a good alternative(can be overhauled stylistically but think it's more readable and simple(can change back to true/false if wanted). Going to tackle pagination next. 

https://github.com/EqualifyEverything/equalify/tree/233-update-report-editor-page

**Comment by bbertucc** [comment]
This was completed in our yet-to-be-released v1. Closing it here to avoid redundancy.
