### ISSUE TITLE
Refactor Equalify within the Symfony Framework

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#234]
## What problem is the feature trying to solve?
Equalify is currently built with just vanilla PHP. We intentionally avoided abstraction and theory in architecting our codebase. That decision was originally made to make the codebase accessible, giving folks new to coding the ability to engage. Unfortunately, working with a plain code base didn't attract folks new to coding. That's because many folks new to coding jump in via a framework and not a language. For example, I had folks tell me they knew Drupal or WordPress but not PHP. 

An additional problem with avoiding a framework meant we couldn't leverage existing documentation and community, beyond PHP.net resources. PHP.net is great, but it doesn't have the community channels and opinionated architecture that a framework has. Leveraging existing more opinions documentation and community would allow us to share ideas with a larger network of users. We could also reference thought behind the features we shipped that didn't just come from our own minds. 

Finally, without a framework Equalify has exposed itself to many bugs and vulnerabilities. Frameworks have features that go through many rounds of testing before they are shipped. Without a framework, we are again just relying on our small community. 

## Desired Solution
Perhaps we refactor Equalify so it's built from Symfony's framework? Symfony has been in active development for many years and has a robust community. I'm also impressed with  the features Symfony offers and its ability to just be used as components if we decide to turn Equalify into a framework of its own (for example, Drupal 8 leverages Symfony itself). 

## Alternatives
We could keep working from vanilla PHP or use other frameworks. Vanilla PHP has the problems I discussed before. We would need to invest more in testing and documentation if we kept building without a framework. 

If we used a different framework, I don't know quite what we would use. I tried Drupal, Laravel, and WordPress in early days of Equalify. Drupal and WordPress were a bit too opinioned, forcing us into business logic that didn't fit our goal of creating an accessibility platform. Laravel is sleek and has a growing community, but it seemed like Equalify would be stuck as a Laravel app if we went with them. Also, the Laravel community has very different values than this project has (they seemed way more interested in making lots of cash via commercialization than making positive impact).  

## Technical Details
TBA

## Next Steps
Before I move forward with refactoring, I imagine I'll have to do the following:
- [ ] Further weigh the pros and cons with a wider community than myself. Key questions: Are my assumptions correct? What is the time and costs associated with refactoring? Would more people indeed contribute to an Equalify + Symfony project? Would the code indeed be more bug free? _Please comment!_
- [ ] Add Equalify's requirements so that refactoring can make sure to meet Equlify's needs. (Eg: Equalify must have a folder called "integrations" that can include distinct sub folders and files to create functions that manipulate core Equalify functions).
- [ ] Learn Symfony better. The core team should be abreast with concepts, development, and the community of Symfony.

**Comment by zersiax** [comment]
It's a tricky situation. Laravel is, essentially, just a bunch of Symphony components with a diabetic amount of syntactic sugar first and foremost, after which they've been adding their own tooling and such to things. And a lot of people liked that approach, so it's the most popular framework by quite a mile (It looks like Laravel uptake is literally about 10 times as high currently). Laravel's learning curve is significantly shallower than Symphony's, and the community, divisive as it is, is quite a bit larger as well which translates to more content out there on the web for it, more mature third-party packages that work with it etc.
The default "dumb" templating language for itis called Blade, but they're moving more and more towards something they call LiveWire, which is essentially a way to do JS-like instant interactivity using PHP. To my knowledge, Symfony doesn't have an eqivalent to this, but both of these frameworks are based on a bunch of components so you can probably pick and choose up to a point.
Symfony is primarily advantageous when applications grow very large, as it is more modular and allows you to deviate from the tried and true MVC pattern that Laravel, Rails, Django, asp.net etc. tend to favor.
I guess the bottom line is, if you want to focus on developer uptake and get more contributors in, go Laravel. If you want to deal with Symfony's added complexity which some seasoned PHP devs will prefer but increase the learning curve for the project, go Symfony :)

**Comment by TolstoyDotCom** [comment]
It's possible to just use parts of Symfony as I did in the last push. It'd be a plain PHP project that uses Symfony components, not a full-on Symfony (or Laravel) project. It'd be tied to Symfony, but not as closely as if it was a full Symfony project. Doing it that way would also make it easier to make into a Drupal module.

**Comment by bbertucc** [comment]
It's always great to hear from you both, @TolstoyDotCom and @zersiax! Falling in love with Synfony at 3AM probably requires some sober reflection later in the day. 

This issue by no means should stop any work on twig templating or fixing the bugs @TolstoyDotCom mentioned. As @TolstoyDotCom, the beauty of Symfony is that we can use components in future work.

> It's possible to just use parts of Symfony as I did in the last push ...

"Unlimited flexibility within reason" is the principle I'm operating under. 

Users have told me they need certain features (#204) by Decemeber (when many universities start procurement). I also need to remember that the open core of this project needs a "crust" to pay for continued development. That said, users might not buy what they say they want and we'll have to pivot to reach sustainability. Flexibility within reason is key.

> ... that way would also make it easier to make into a Drupal module.

I tried building Equalify as a Drupal module, WordPress plugin, and Laravel project. Those frameworks were too opinioned. I found myself spending more time hacking their work and adding lots of dependencies than building new features. For whatever reason, I never came across Symfony. What I like about Symfony's framework is that it seems to get out of the way of building features.

> Laravel is, essentially, just a bunch of Symphony components with a diabetic amount of syntactic sugar 

Love that image!

> I guess the bottom line is, if you want to focus on developer uptake and get more contributors in, go Laravel. If you want to deal with Symfony's added complexity which some seasoned PHP devs will prefer but increase the learning curve for the project, go Symfony

We're going after enterprise users who have over 10,000 pages. There are about 78 WCAG 2.1 standards that could, in theory, get an alert on every page. That's about 7,800,000 on 10,000 pages. Creating infrastructure that can support that kind of volume, while also be customized to particular "pro" use cases, is key to our work.

**Comment by bbertucc** [comment]
I'm going to close this issue. After speaking to @TolstoyDotCom, I realize that doing a total refactor will take our attention away from key work that needs to get done right now. That can change later - especially since we're using Symfony components.
