### ISSUE TITLE
Pluggable authentication, users, permissions, etc

### ISSUE THREAD

**Issue by TolstoyDotCom** [bbertucc/equalify#239]
## What problem is the feature trying to solve?
Have a pluggable authentication system with user objects, permissions, etc. On local installations it would default to allowing everything. On other installations the user would need to log in and have the proper permissions to do various things.

## Desired Solution
Just mimic what Drupal does, in a minimized way. The container will have a 'current_user' service that represents the current user. Unlike with Drupal, no proxies would be involved: you'd get a user object with all the data on the user: ID, name, etc. Rather than fields, the User object would have a hashmap where extra data could be stored. The User object would be persisted to just one database table (instead it being spread over a base table + tables for fields, etc). The User method that would be used most is hasPermission(). That takes a string representing the permission and it returns a boolean.

For local installations, hasPermission() would always return TRUE. In other cases, things could be hard-coded, like a specific set of permissions only return TRUE if the user is an admin, etc. Or, roles could be used. To avoid all the code that would be involved in making things like Drupal, there could just be a small, fixed set of roles (admin, content editor, visitor, etc). A JSON or YAML file would have the permissions each role is given. That would avoid having to write something like Drupal's permissions page.

In any version, each entry page would have to start the session and initialize the container and the current_user service. To avoid duplication, it's important to minimize the number of entry pages; preferably every request would go through index.php.

**Comment by bbertucc** [comment]
This addresses my concern of requiring accounts on a local version. I'm adding this to the Beta 1 Release, and assigning you to it. Please proceed.

**Comment by bbertucc** [comment]
The lastest push resolves this issue
