### ISSUE TITLE
Create New Header Template

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#247]
## What problem is the feature trying to solve?
With #204, we developed a simplified user experience (UX). That new UX requires a revised header that isn't currently implemented.

## Desired Solution
The new header will include the Equalify logo with the Alt Tag ("Equalify") that is linked to the All Reports view. There would also be four key navigation items: Add Alert, Reports, Settings, and Account. Each navigation item should have an icon to increase the accessibility of the content items. The selected page should be highlighted. "Account" would only be visible on the cloud version. 

## Technical Details
- A wireframe of the header is available here: https://miro.com/app/board/uXjVMX3i1XA=/?share_link_id=156482074960
- All templates should use the latest version of Bootstrap as a guide for markup and styling.
- The logo is available here: https://github.com/EqualifyEverything/equalify/blob/main/logo.svg
- Coded templates must meet WCAG 2.2 requirements. Pay particular attention to making sure the items are navigatable using the tab key and that they include an active state that is distinguishable. 
- This template will be referenced in other twig files.
- #226 adds more details about the UX related to this issue.

## Steps to Complete
- [x] Develop Twig template.
- [x] Hookup proper routes.

**Comment by bbertucc** [comment]
This issue is related to #226

**Comment by jwgoedert** [comment]
On it, will work on this tandemly with the All Reports view and others to come-thanks!

**Comment by jwgoedert** [comment]
Creating initial structure on branch #247-create-new-header-template deciding between font-awesome or direct svgs in nav bar

**Comment by jwgoedert** [comment]
<img width="658" alt="image" src="https://github.com/EqualifyEverything/equalify/assets/6878159/4e250cbc-72b2-4a19-85e6-fd942bf26641">
Pivoted to take a more static approach. Removing data/svg elements from controller and plugging in directly to main-header.html.twig for the moment to solidify functionality. Was having issues getting the header to populate the navItems when extending other templates such as "All Reports" from the header template. @TolstoyDotCom maybe I can get your input on this after I flesh out this latest branch. New approach in #247-create-static-header-template, will prune and clean up after final approach is decided on.
(still working on styling, tab nav, and active states)
