### ISSUE TITLE
Installation fails with MySQL version =< 5.6

### ISSUE THREAD

**Issue by azdak** [bbertucc/equalify#252]
## Steps To Reproduce
1. Follow documentation to install on system with MySQL 5.6 or lower

Example of error thrown:
`
Fatal error: Uncaught mysqli_sql_exception: Specified key was too long; max key length is 767 bytes in Z:\IIS Projects\php-sandbox\equalify\models\db.php:53 Stack trace: #0 Z:\IIS Projects\php-sandbox\equalify\models\db.php(53): mysqli->query('CREATE TABLE `t...') #1 Z:\IIS Projects\php-sandbox\equalify\models\db.php(759): DataAccess::query('CREATE TABLE `t...', Array, false) #2 Z:\IIS Projects\php-sandbox\equalify\install.php(18): DataAccess::create_tags_table() #3 Z:\IIS Projects\php-sandbox\equalify\index.php(37): require_once('Z:\\IIS Projects...') #4 {main} thrown in Z:\IIS Projects\php-sandbox\equalify\models\db.php on line 53
`

## Additional context
Error is due to [table prefix limitations on older versions of MySQL](https://stackoverflow.com/questions/1814532/mysql-error-1071-specified-key-was-too-long-max-key-length-is-767-bytes). Documentation should reflect minimum version requirements.

**Comment by bbertucc** [comment]
The latest push resolves this issue
