### ISSUE TITLE
Simplify Scan Success Message

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#275]
## Issue
After the scans are processed, the screen reader begins reading off the entire list of results in one contiguous chunk. In the case of this testing that was a list of 16. That's overwhelming and way too verbose. I recommend just having some messaging that "x" number of scans completed, provide a semantic heading for the user to easily jump to the results on their accord, and inform of the heading in the message. It so happened I stopped it speaking after the fifth or sixth item and was looking for the results which I assumed would be preceded by a heading. When that wasn't the case, I encountered the button to process 20 scans again. Not a11y per se, but it could be a little misleading for someone if they're not sure that the scan already completed, maybe they missed the alert (stopped the screen reader/was doing something else and missed it, etc).

## Solution
Update [process_scans.php](https://github.com/EqualifyEverything/v1/blob/main/actions/process_scans.php#L367C10-L367C25) so success message just counts the results instead of doing a LI list. See `$success_message`.

**Comment by jwgoedert** [comment]
Still not 100% sure on the desired outcome with this. Left previous code commented out in case it needs to be added is a separate section.  Currently returns a success message with only the count.  
<img width="1039" alt="image" src="https://github.com/EqualifyEverything/v1/assets/6878159/8d0ebcf9-32ca-4955-908e-fb62d53fc48c">
*added a space before 'results'

**Comment by bbertucc** [comment]
Yeah. Let me ask about this. Would you mind moving the updates to a separate branch then do a PR into the branch you were working in? That way I can merge the other updates while we still research this.

**Comment by jwgoedert** [comment]
For sure, I've previously done branches by issue and PRed to keep things separate and clean, gets a little branch heavy but can prune after merge. If that's too muddy I can revert to a single dev branch and PR into the  37-nvda... branch?

**Comment by bbertucc** [comment]
o yeah, branches by issue with PRs works great!

**Comment by bbertucc** [comment]
As noted, we're going to close this until we have more information.
