### ISSUE TITLE
React-based Fronted for Equalify

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#280]
## What problem is the feature trying to solve?
Our frontend development moves as fast as PHP, which isn't that fast.

## Desired Solution
React will make us faster and get to play with the cool kids.

## Alternatives
I would be open to other frontend frameworks.

## Technical Details (Optional)
- I could probably just supply a dev with our data schema. They would go off and create the frontend, mimicking what Equalify is doing now. Then we can figure out how to integrate the frontend into the repo.
- As I [noted](https://github.com/EqualifyEverything/equalify/issues/278#issuecomment-1995639047), we'll probably need to know how to deal with our currently incomplete API. If not, this issue is blocked by #283
- Many components currently have JS that demonstrates how we're dealing with our API. Example: https://github.com/EqualifyEverything/equalify/blob/dae3be0b02338f36ca9bba0154cbea3dc6437870/components/message_list.php#L36

**Comment by wittjeff** [comment]
Do you have an opinion re CSS structure philosophy?  The two big ones I see in React-world right now are Bootstrap and Tailwind.  Converting from one philosophy to the other is prohibitively complex, and preferences seem to be largely religious.  See for example https://blog.logrocket.com/comparing-tailwind-css-bootstrap-time-ditch-ui-kits/#:~:text=Bootstrap%20is%20a%20component%2Dbased,it%20has%20no%20prebuilt%20components.

**Comment by eekbk** [comment]
I'm interested in picking this ticket up. 

React documentation suggests using a framework like Next.js for server-side rendering, SEO, and various optimizations, but I understand Equalify's preference to maintain simplicity and inclusiveness by avoiding unnecessary frameworks. Would you prefer a standalone React frontend to avoid the added complexity?

[https://react.dev/learn/start-a-new-react-project#can-i-use-react-without-a-framework](url)

**Comment by bbertucc** [comment]
> Do you have an opinion re CSS structure philosophy? 

Bootstrap is what we currently use, so I would suggest using that, @wittjeff.

> Would you prefer a standalone React frontend to avoid the added complexity?

Yes, @eekbk, and.. we do use frameworks when the framework simplifies work. An argument could be made that something like Next.js actually simplifies development. I would just ask anyone who takes on this task to explain how their solution simplifies development and what they will do to make sure devs with 2-3 years experience could understand new code.

**Comment by bbertucc** [comment]
@eekbk - Would you post a proposal of how you would create our front end? If you need a budget as part of this project, feel free to post in #278. I'll be reviewing bountied proposals there. Otherwise, you can post your proposal here and we can work toward it turning into a PR with clear tasks.

**Comment by wittjeff** [comment]
I don't have any objections to bootstrap, but I note that there seems to be a community affinity between next.js and tailwind.css. And getting Bootstrap front-end widgets to load cleanly with next.js [can be a little kludgy](https://blog.logrocket.com/handling-bootstrap-integration-next-js/)

**Comment by bbertucc** [comment]
The benefit of Bootstrap and our current UX is that we have already user tested it. That would spare us some of the issues of jumping into a totally unique UX with a different style.

That said, I'm really open to any frontend style system @wittjeff so long as someone can tell me how it makes Equalify more accessible. That means both an accessible user interface and easy to contribute-to code base. 

This issue is trying to solve the problem that most frontend people don't mess with PHP. React and other frontend technologies allow for more standardization, which increases opportunity for contribution. I would embrace any solution that works toward greater openness.

**Comment by bbertucc** [comment]
Added a few notes to the technical details.

**Comment by bbertucc** [comment]
Closing this issue for #298 - congrats @eekbk!
