### ISSUE TITLE
Launch Version 1!

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#304]
## Overview
We're ready to go! Or will be very soon.

This ticket details what I will do to launch Equalify Version 1.

The process can be broken down into four parts:
1. **Final Buildout Push**. We're in the last weeks of buildout! Our[ project board](https://github.com/orgs/EqualifyEverything/projects/2) details that push. I will be responsible for pushing the develop to our glorious launch.
2. **Sales and Marketing**. We'll need to sell Equalify in order to prove our sustainability. "Selling" Equalify doesn't mean paywalling everything. Equalify is Open Source Software. We have to sell Equalify as a movement to promote fixing accessibility issues. A large part of this will be our work with WordPress (see [Project Eudaimonia WP](https://github.com/equalifyEverything/eudaimonia-wp)). I'm also looking forward to supporting @kevinandrews1 Higher Ed outreach initiatives. Our initial users are from Higher Ed orgs.
3. **Support**. With Version 1, we start to get customers. They'll all know that they can reach me 24/7 to address any issues and anyone can [Join our Slack](https://join.slack.com/t/equalifyapp/shared_invite/zt-1sfbgf0fa-CzIHlbFOs0Ww1iSTK4LQ2w) or add a GitHub issue for community support.
4. **The Future**. Good tech evolves. We got to keep an eye on the future, as we deliver this version 1. Super pumped to get in the trenches with @azdak @heythisischris @wilsuriel03 @jwgoedert @kevinandrews1 and everyone else who contributes. We'll learn from early users and build better. For More: Visit the [#future channel in Slack](https://equalifyapp.slack.com/archives/C075ESQDPS5).

## Tasks
I can break down my work into discrete tasks:
- **Meeting Management**: Managing a weekly contributor meeting, WordPress accessibility-testing meeting, and any other meetings that keep things moving.
- **Budgeting**: I've been collecting budgets for each project. I'm the one to make sure we're on track to deliver with cash in the bank.
- **Making a Fool of Myself on tXtter**. Someone's got to do it, right? Many of the biggest connections I've made have been on Social Media.
- **Responding to Clients**: Like I said, I'm the one on the hook when clients call.
- **Responding to Contributors**: As with clients, I'm here 24/7 for contributor needs. Slack. Call. DM. Whatever. I'm here for you!
- **Random Outreach**: There is a need for random outreach. This would include participating in accessibility meetings that pop-up, chasing leads, and maybe even making a fool of myself on Twitter. Random outreach has led to incredible opportunities and ideas, but I'll work to engage in random outreach only when all other tasks are done. 

## Outcomes
For my tasks to be successful, I hope to see:
1. 100k Equalified Issues by 9/1: Equalifying an issue is fixing an issue. I’ve set a personal goal of logging 11M fixes by February. I will be happy with 100k logged fixes by September. This will largely come with our work with WordPress.
2. Three Customers by 9/1: To sustain our work, we need customers. I’m not super experienced at Sales, so this is mostly a stretch goal to see what works and what doesn’t.

Clearly defined success goals help push a project forward and understand areas for improvement. I’ll make a note to check in on our success goals at the first contributor meeting of every month, then we can iterate as we need.

## Hours and Cost
Equalify's "Founder" role is a 24/7, 365 position. Except for the time my family needs and a philosophy meeting on Sundays at 11:11, my whole world is Equalify. For that work, I propose a salary of $3,333/mo for three months (June, July, August). September 1, we'll revisit.

## Let's do it?

I’m opening this up to Equalify contributors for approval. Feel free to add any comments. Comments will be brought to our contributor meeting on May 27 at 11:11 CST where contributors will add any amendments. We'll keep comments open for 24 hours for async replies. If the proposal isn't rejected by contributors by May 28 at 11:11 CST, I'll consider this good to go. Contributor Meeting URL: https://lu.ma/tomato

**Comment by bbertucc** [comment]
Tagging past contributors (in code and ideas), since they will be the ones to accept/reject/question my contract to "Sell the thing!". @mgifford @kreynen @eekbk @alphex @kreynen @jrchamp @wilsuriel03 @jwgoedert @TheBoatyMcBoatFace @BaronWolfenstein @ebertucc @hcwiley @j-mendez @dgradcliffe @ellieya @szepeviktor @huyszn @heythisischris @zersiax @joedolson @joelhsmith 

I created this after existing contributors agreed to draft projects to add to our [project board](https://github.com/orgs/EqualifyEverything/projects/2).

Curious if you have any feedback. Feel free also come to the next contributor meeting:  https://lu.ma/tomato

**Comment by bbertucc** [comment]
Discussed this on our Contributor Call call with the team today. There were no objections.

**Comment by kevinandrews1** [comment]
I couldn't attend the contributors call this week, but I have no objections. The enthusiasm, determination, and passion are palpable and infectious. Thank you for this and the transparency @bbertucc!

**Comment by bbertucc** [comment]
Thanks @kevinandrews1!

I guess that means this issue is good to go.

I look forward to serving you all.

Please hold me to it!

Somewhat related: @josephjacks [posted on X](https://x.com/JosephJacks_/status/1795497964674388209): 
> The best open source projects are "benevolent" dictatorships! 

Linking to one of the first uses of Benevolent Dictator for Life(BDFL): https://www.artima.com/weblogs/viewpost.jsp?thread=235725

I'm striving for Interim Benevolent Dictator (IBD) status, probably being replaced by someone who is blind or relies on assistive tech for another reason. Please hold me to that too!

**Comment by kevinandrews1** [comment]
Most certainly will @bbertucc! Btw, on that note, for some reason I couldn't tag you on this [issue](https://github.com/EqualifyEverything/equalify/issues/333), so pinging you here in addition to Slack on my outreach proposal. I wonder if, with your blessing, we should wrap your working with me on the outreach efforts as part of the pre-launch bucket of work in the launch plan. I look forward to your feedback on this.

**Comment by bbertucc** [comment]
> I couldn't tag you on this https://github.com/EqualifyEverything/equalify/issues/333, so pinging you here in addition to Slack on my outreach proposal.

Monday, we can create an equalify-outreach repo to organize info in. We'll make sure you can ping me through that.

**Comment by kevinandrews1** [comment]
Thanks @bbertucc let me know when the new repo's created!

**Comment by bbertucc** [comment]
Closing this as we are finished with the project
