### ISSUE TITLE
Get Organizational Repo Licenses and Contributor Agreements Inline

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#307]
I've been really bad about staying on top of getting contributor agreements and adding licenses to the Equalify org repos.

Good contributor agreements are super important because many major organizations will not use code without them. The contributor agreement I've been recommended most is this: https://www.eclipse.org/legal/committer_process/EclipseMemberCommitterAgreement.pdf

I'll need to make sure @azdak @heythisischris @wilsuriel03 @kevinandrews1 @hcwiley and @jwgoedert signed these agreements.

As for Licenses, every repo in the Equalify organization should have an [approved Open Source license](https://opensource.org/licenses) attributed to Equalify Inc.

I have been dragging my feet on licenses because we haven't had enough business to really decide what license suits us best. For now, maybe we can just add a LICENSE.MD file to each repo that says:
```
All code is owned by Equalify Inc. 

We are waiting for some business necessity to decide which license we will publish this code under, but we are committed to releasing all Equalify code under an Open Source license approved by the Open Source Initiative. Visit https://opensource.org/licenses for a full list of approved licenses.

Feel free to add an issue in this repo if you have a business reason why we should adopt a specific license.
```

**Comment by bbertucc** [comment]
Discussed this on the contributor meeting. @heythisischris mentioned that MPL, which we might look into.

**Comment by bbertucc** [comment]
Licenses should be added, and I pinged everyone in Slack about adding their CLAs to our CLA repo: https://github.com/EqualifyEverything/equalify-cla

**Comment by bbertucc** [comment]
@azdak your license is the only one we need before I can close this issue. Is there anything else you need before I can do that? This is becoming more pressing now because we have to do Vendor Risk Assessments for Higher Ed institutions. LMK!

**Comment by bbertucc** [comment]
Just noting: On our contributor call yesterday, @azdak said he would jump on this.

**Comment by azdak** [comment]
Added
