### ISSUE TITLE
Duplicating Properties

### ISSUE THREAD

**Issue by joelhsmith** [bbertucc/equalify#310]
## Basic Bug Description

When I scan an updated sitemap it creates a whole new duplicate property.

## Steps To Reproduce
https://duke.box.com/s/3j7q2wcqk4smm6rbvavmhdqsckkrqwmd

## Expected behavior
Just scan and not make a new Property.

## How does fixing this issue help fix accessibility issues?
If the user interface creates a new property every time I scan, then I can't manage or use the product in an effective way. How do I know if I delete a duplicate property if I am deleting a new one or an old one? How do I know if I am deleting all my work?

**Additional context**
I created a bug report for a similar issue that has disappeared.

**Comment by bbertucc** [comment]
Super weird! I'm looking into this.

**Comment by bbertucc** [comment]
This should be fixed @joelhsmith

I also went ahead and cleaned out the duplicate data from your account.

**Comment by joelhsmith** [comment]
Hi @bbertucc this is not fixed. Please see new video of same behavior. https://duke.box.com/s/kr7uhpb8e7ei386gfirn9kn33xnt07f7

**Comment by joelhsmith** [comment]
Reopened with new video demo.

**Comment by bbertucc** [comment]
> Hi @bbertucc this is not fixed.

O no! What version browser are you using?

It was working for me, but I can try to recreate your environment and test again.

**Comment by joelhsmith** [comment]
I was using latest version of Chrome in both of the video demos. I replicated it one time after you cleared out data from my account. I have not been able to replicate it today. I banged on it for a while to make sure. I think we can close it. Has there been any backed code change that would account for the bug going away? I am very happy it is not happening anymore, but its also concerning when an error can be replicated twice on video but goes away without cause.

**Comment by bbertucc** [comment]
We haven't updated any backend code since the video. 

I suspect you were seeing a cached version of the site when you tested it a second time.

The bug was in how we saved report names. Here: https://github.com/EqualifyEverything/equalify/commit/645fcecbe5821020fc4876ea324e4c55ef21a992

I'll close this issue now. Feel free to open it if you see it pop up again.
