### ISSUE TITLE
Scan Queue is missing most URLs

### ISSUE THREAD

**Issue by joelhsmith** [bbertucc/equalify#313]
## Basic Bug Description

Scan Queue is missing most URLs in Page URL column

Site map: https://a11y-sitemaps-a11y-assessments-27359e4d540152ef4c5aab0890155427.pages.oit.duke.edu/sitemap-duke-2.xml

## Steps To Reproduce
1. With Property open...
2. Click "Send to Scan"
3. Click "Scans"

## Expected behavior
See a list of URLs to be scanned.

## Screenshots
https://duke.box.com/s/w1um8gvaldfgxs45gzj968cc75cb2nnd 

## How does fixing this issue help fix accessibility issues?
We need to know what we are scanning.

**Comment by bbertucc** [comment]
Yes. This is something we're aware of.  

If Equalify hasn't scanned the page yet, it won't know what the page URL is.

Our Version 1 solves this, which we're planning to rollout in early July.

**Comment by bbertucc** [comment]
This is fixed with V1
