### ISSUE TITLE
Accessibility Bugs: Charts Lines need to be alternating styles and contain labels

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#316]
@aardrian reported that the lines on our chart are indistinguishable because we are only distinguishing them by color. Many types of color blindness result in the inability to distinguish colors. 

Perhaps we one of the lines can be dashed and the other can be solid, in addition to different colors?

We also need to add labels or a key so people know what they are looking at.

**Comment by bbertucc** [comment]
@wilsuriel03 this probably should be addressed with our Version 1.

**Comment by bbertucc** [comment]
This is also super important, but I don't see it making it into our Version 1. Tagging @wilsuriel03 so he sees this and can factor it into mockups for our next version.

**Comment by kevinandrews1** [comment]
Did @wilsuriel03 complete this, @bbertucc?

**Comment by bbertucc** [comment]
No @kevinandrews1 - as my note suggested, we're not focusing on this for this version 1 push. But of course you're welcome to state otherwise.

**Comment by kevinandrews1** [comment]
@bbertucc  The way I'm reading this we're not doing the chart at all for v1? Or if we are, then it needs to include the a11y. The charting is a critical piece and if we have it in then it *has* to be accessible.

**Comment by bbertucc** [comment]
Sounds good @kevinandrews1. I'm reopening this issue. @wilsuriel03  can you look into distinguishing the chart lines in different ways? Like one line can be dashed and the other can be solid?

We also will need to do #323, so you might want to look at that in tandem.

**Comment by wilsuriel03** [comment]
@bbertucc , this was fixed. the chart show a solid line for "Equalified", and a dashed line for "Active". Also the lines have different colors and they also have a thickness to be more visible.

**Comment by bbertucc** [comment]
@kevinandrews1 this is ready for your review

**Comment by kevinandrews1** [comment]
These are visual representations just not color alone, so I need a pair of eyes for this one to verify @bbertucc.

**Comment by bbertucc** [comment]
@kevinandrews1 I can see this is fixed. Leaving it open though for you to close on Monday.
