### ISSUE TITLE
Error if invalid URL supplied

### ISSUE THREAD

**Issue by chasebrook** [bbertucc/equalify#32]
If website doesn't exist, this error comes up: 
Fatal error: Uncaught Exception: The URL "journeys.dartmouth.edu/billtest02" is not valid output in /var/www/html/models/adders.php:80 Stack trace: #0 /var/www/html/actions/add_site.php(42): wordpress_site_adder() #1 {main} thrown in /var/www/html/models/adders.php on line 80

**Comment by bbertucc** [comment]
Thanks! Looking into this.

**Comment by bbertucc** [comment]
This if fixed with our latest release.
