### ISSUE TITLE
Multiple duplicate Properties generated when user has invalid sitemap

### ISSUE THREAD

**Issue by joelhsmith** [bbertucc/equalify#320]
Issue 1: Equalify Properties are duplicating with user error. To reproduce:

1. Upload a faulty sitemap, with syntax errors in it.
2. Choose "Settings" from the top menu.
3. Choose the Property.
4. Enter a faulty sitemap in 'sitemap url' field.
5. Click "Send to scan".
6. Equalify will respond with "2024-04-22 13:55:26: Property results are not formatted correctly" in light grey next to the "Send to Scan" button.
7. Choose "Reports" from the top menu.
8. Choose "Settings" from the top menu.
9. You will see a new duplicate "Property" for _every_ failed scan.

Link to see image of duplicate Properties: https://duke.box.com/s/f3fil37nrldk9nirrijp312avjqiusv4

Expected behavior:
Not generating a new Property for each failed attempt to Scan new potentially faulty sitemap.

Sidenote: My old sitemap.xml was accepted and scanned fine last month. See old version here:
https://github.com/joelhsmith/debug-examples/commit/5b4b94a7e8d4c10a054f41bc4405e83e010e0e62

Not it does not work. Maybe there is new validation going on since last month?

I have uploaded a new valid sitemap:
https://joelhsmith.github.io/debug-examples/lh-tests/sitemap.xml

I get the same error as the previous sitemap.

Issue 2: Sitemap is cached, maybe?
The new sitemap above is valid and I get the same error as I had with my invalid sitemap.

**Comment by kevinandrews1** [comment]
Hey @joelhsmith, where you testing this? I Would love to get my hands in/on this.

**Comment by joelhsmith** [comment]
Managed Equalify equalify_account_41

**Comment by bbertucc** [comment]
@joelhsmith we're updating our scanning system to support the new [Equalify Schema](https://github.com/equalifyEverything/equalify-schem). We are still a few weeks away from rolling out the update, but LMK if you run into a mission-critical need for the scan and I'll jump you in front of the line of people we're transferring to the new system.

**Comment by bbertucc** [comment]
This issue is fixed with V1.
