### ISSUE TITLE
Refactor out Monitor console.log to utilize centralized logging via logz.io

### ISSUE THREAD

**Issue by azdak** [bbertucc/equalify#326]
We've added telemetry tracking, next step will be replacing internal console logging with a shared logger class/object to centralize across servers, allow log access without having to ssh in, etc.

**Comment by bbertucc** [comment]
Hey @azdak - is this still open? We're trying to organize all our issues.

**Comment by azdak** [comment]
Yes, still open, but more a convenience thing than mission-critical (also already implemented in monitor, so adding to scan should be mostly a copy+paste/drop-in)

**Comment by bbertucc** [comment]
Cool. I'm going to close this @azdak so we can focus the issues on mission-critical fixes. But feel free to jump on it.
