### ISSUE TITLE
Build First Version of Raga

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#328]
## Overview
These requirements may shift through user testing, but hold to a general expectations through my experience doing manual tests:

- [ ] Chrome Extension
- [ ] Login to Equalify 
- [ ] Select existing Property that has `propertyDiscovery` set to "manually_added"  (via `/get/properties` API call) or add a new property with `propertyDiscovery` set to "manually_added" (via `/add/properties` API call)
- [ ] Right click in inspector or use Quick Key that doesn't interfere with screen reader to capture content.
- [ ] Capture `node` data (HTML snippet + targets) and message (existing messages can be selected via [autocomplete](https://github.com/alphagov/accessible-autocomplete) of `get/messages` API call)
- [ ]  On submission, send data formatted in [Equalify Schema ](https://github.com/equalifyEverything/equalify-schema) to api.equalify.app via `/add/results`
- [ ] Return success/failure status with message
- [ ] Test with Slack community

NOTE: The Equalify API is still being built. You can see working docs and ping the maintainer of that on this issue: https://github.com/EqualifyEverything/equalify-api/issues/3

If needed, an Equalify SVG is available here: https://github.com/EqualifyEverything/equalify/blob/main/logo.svg

**Comment by bbertucc** [comment]
Updates from 5/29 Call:
- Everything is bootstrapped
- Chrome Extension is Architected
- Implemented Authentication Paradigm w/ API to auth to

Still To Do:
- Test on Screen Reader
- Finalize handoff to @jwgoedert
- Can @heythisischris provide a .ts API file? Or how else should we think about integrating?
- Run a production and get it distributed
- @bbertucc will get Chrome Extension Store Login
- @bbertucc will send his PM notes and @hcwiley will send the second payment info.

Video available here: https://youtu.be/ikv6GfXPRu0

**Comment by kevinandrews1** [comment]
Nice! I see the first todo is screen reader testing. What sort of timeline are we looking at to have the extension completed? I'm available to test throughout next week, if needed/that timing works @bbertucc and @hcwiley

**Comment by bbertucc** [comment]
Going to close this issue for now. We're in the sprint to deliver V1. This is a very important issue, but we need to prioritize other issues right now. Please let us know if you think this should be V1 or when we should re-open this issue!
