### ISSUE TITLE
RDS Database has Inconsistent Representations of OG Database 

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#342]
## Overview
I found some inconsistencies between the new RDS database and the original (OG) database. 

Here is a running list of RDS inconsistencies:
- **"properties" table column "sitemapUrl" should be "propertyUrl"**: this is a minor change that will better reflect what data is in properties.
- **"messages" table is missing "messageType" column**: The scan outputs has both violations and errors. We need to track what type of issue is being created.
- **"enodes" table is missing "nodeTargets" column**: The scan outputs targets in addition to HTML. These targets help us identify where the issue is.

I'll need those inconsistencies resolved to properly transfer data from the OG database.

## Before We Close The Ticket

- [x] Check to make sure inconsistencies are taken care of in table.
- [x] Make sure API properly uses tables (add property, remove property, run scan and get_results to see if messages and nodes were properly created)
- [x] Make sure frontend is still working with updates
- [x] If any frontend changes were updated, make sure that Accessibility is still good to go.

**Comment by bbertucc** [comment]
So I can complete #348, I'm just going to make my script output PostgreSQL in a format that anticipates the inconsistencies being addressed.

**Comment by bbertucc** [comment]
@heythisischris any update on this? I'm blocked from importing content until this is done.

**Comment by heythisischris** [comment]
Completed! I renamed `sitemapUrl` to `propertyUrl` inside of the `properties` table.

As for `messages`, we already have a `type` column which tracks `messageType`.

Same for `endoes`- we have a `targets` column which tracks `nodeTargets`.

**Comment by bbertucc** [comment]
Should I close this? It has nothing to do with accessiblity.
