### ISSUE TITLE
Make sure sitemaps are scanned and results are showing correctly

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#343]
Currently the API and fronend only report on single page results, even if "Sitemap" is selected from the discovery process.

**Comment by bbertucc** [comment]
@heythisischris any update on this? i'm still seeing an individual page vs sitemap when scanning under the scanning discovery process

**Comment by heythisischris** [comment]
We've got single/sitemap URLs working now! You can go ahead and close after validating.

**Comment by bbertucc** [comment]
Note to self: This is done. But I didn't want to close it because our current handbook has @kevinandrews1 closing issues. We should discuss this process at our next contributor meeting because I think I should be able to close it. Maybe we just say it has to be closed by Kevin or I, if there is no a11y problems?
