### ISSUE TITLE
Migrate staging DB schema to production

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#347]

**Comment by heythisischris** [comment]
Staging DB schema has been successfully migrated to production!

**Comment by bbertucc** [comment]
Note to self: This is done. But I didn't want to close it because our current hanbooks has @kevinandrews1 closing issues. We should discuss this process at our next contributor meeting because I think I should be able to close it. Maybe we just say it has to be closed by Kevin or I, if there is no a11y problems?
