### ISSUE TITLE
Add Password Reset

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#349]
## What problem is the feature trying to solve?
We currently have no way to reset a password.

## Desired Solution
A password reset link on the sign-in page. This link should allow a user to reset their password.

**Comment by bbertucc** [comment]
Assigning this to @heythisischris, but feel free to change if you're not the one to handle it.

**Comment by heythisischris** [comment]
Completed! You should now be able to reset your password.

**Comment by kevinandrews1** [comment]
@heythisischris Can we reopen this and assign it to me? I wanna test for accessibility especially a critical workflow such as this--resetting a pw. Thanks.

**Comment by heythisischris** [comment]
Reopened it @kevinandrews1!

**Comment by kevinandrews1** [comment]
@heythisischris the textfield needs to have email as an explicit label or associated with aria-labelledby (I recommend explicit). Tested w/both latest JAWS and NVDA. Just says edit so you don't know the purpose of the field only that's an editable textfield.

**Comment by bbertucc** [comment]
@heythisischris mind looking into the issues Kevin reported?

**Comment by bbertucc** [comment]
@kevinandrews1 - Can you re-review this feature? The update is pushed and it should be working.
