### ISSUE TITLE
Inaccessible error handling on signup

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#350]
When attempting to sign up, after pressing “Continue,” the focus jumps back to the “Confirm Password” field without any programmatic indication  the passwords do not match. The user should receive a clear message indicating that the passwords do not match, and focus should be directed to the relevant message or field. The issue can be addressed by programmatically setting focus on the error message element when the passwords do not match and using ARIA live regions to announce the error to screen readers. programmatically set focus on the error message and use an assertive live region.

**Comment by wilsuriel03** [comment]
Completed ✅

**Comment by bbertucc** [comment]
@kevinandrews1 assigning this back to you to review the update.
