### ISSUE TITLE
Lack of Indication for Verification Form Appearance

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#351]
After signing up, the message “Processing, please wait” appears, but there is no indication that the verification form has appeared on the screen. The initial appearance of the form is currently only visible, with no auditory or other non-visual cues. The same issue occurs when pressing “Verify and Sign Up.” When the “Processing, please wait” message is displayed, users need to be informed when the verification form appears. Currently, there is no indication apart from the visual change, which can be problematic for users relying on screen readers or other assistive technologies. To address this issue, it is crucial to provide clear notifications that the form has appeared, ensuring all users are aware of the change.

**Comment by wilsuriel03** [comment]
complete ✅

**Comment by bbertucc** [comment]
@kevinandrews1 assigning this back to you to review the update.

**Comment by kevinandrews1** [comment]
Hey @wilsuriel03 I tested this. To do so:

- Deleted my account
- Got the message processing please wait but then nothing further (I found I was kicked back to the login screen without any programmatic indication and feedback)
- Signed up and got the alert that the verification code was sent
- Verified but then didn't know the reports screen loaded

**Comment by bbertucc** [comment]
@wilsuriel03 do you mind looking into what Kevin reported? Please ask if you need more clarity.

**Comment by wilsuriel03** [comment]
complete ✅

**Comment by kevinandrews1** [comment]
I deleted and signed up a couple of times @wilsuriel03, but after pressing verify and sign up, I get the processing please wait but don't get the "reports page loaded" message and have to manually check the page.

**Comment by wilsuriel03** [comment]
@kevinandrews1  have you retested this?

**Comment by kevinandrews1** [comment]
@wilsuriel03 This past Saturday, yeah.

**Comment by wilsuriel03** [comment]
do you mind retesting @kevinandrews1

**Comment by kevinandrews1** [comment]
Will do @wilsuriel03!

**Comment by kevinandrews1** [comment]
Hey @wilsuriel03 I deleted and recreated and after verifying I got processing please wait then absolutely nothing. I gave it a good 15 seconds or so then manually checked the page--I was on the reports page. Let me know if you wanna jump on a call or if async--video perhaps--would help.

**Comment by bbertucc** [comment]
@kevinandrews1 do you think you can record a video talking through the issue? I'm also a bit unsure of the issue.

**Comment by kevinandrews1** [comment]
Here's a [video](https://drive.google.com/file/d/18xSJxLuEu4wkTa0X8TOrbexcToyiQZba/view?usp=drive_link) showing on both JAWS and NVDA @bbertucc and @wilsuriel03

**Comment by bbertucc** [comment]
Thanks @kevinandrews1! That was super helpful. I'm going to close this issue and open a few tickets from what I saw:
- #388
- #390
