### ISSUE TITLE
Incorrect Use of aria-readonly Attribute on Input Fields

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#353]
Went to create a report, and the report name input is using aria-readonly. This is a huge no-no. I instinctively thought for some reason I couldn’t type into it. The aria-readonly attribute semantically indicates that the element is not editable but is otherwise operable. It is, in fact, editable, so I don’t know why that’s the case as it can receive input. This issue also appears with many other inputs, such as on the “My Account” screen when updating your name, etc. need to double check  text inputs and ensure this is not being incorrectly applied. this one is certainly a blocker because somebody will inaccurately think they can't type into the fields when this attribute is used.

**Comment by wilsuriel03** [comment]
Complete ✅

**Comment by bbertucc** [comment]
@kevinandrews1 assigning this back to you to review the update.

**Comment by kevinandrews1** [comment]
I get a 404 when I try to create a new report. Adding a new property there's still read only. I also observe this on my account screen. FWIW i'm in incognito as I was this morning.

**Comment by kevinandrews1** [comment]
Oops, nvm, @wilsuriel03 just told me it's not in prod yet. False alarm.
