### ISSUE TITLE
Lack of Feedback and Placeholder Text in Properties Filter

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#357]
When creating a report and selecting the properties filter type, searching for a property (e.g., “testprop” or even just the first couple of letters) does not provide any programmatic feedback indicating that results have appeared. Additionally, the input field uses placeholder text. There should be clear feedback when search results appear to inform users that their search was successful. Currently, there is no indication, which can lead to confusion. Furthermore, the use of placeholder text is problematic as it often has poor contrast and disappears when typing, making it a poor substitute for proper labels. There should also be a straightforward way to search existing properties, as the current method is unclear.

**Comment by kevinandrews1** [comment]
@wilsuriel03 also can confirm when creating a report and you search by URL, for instance, you can't actually select any of the URLs that appear. Need to be able to cycle through the list via keyboard as there's currently no (easy/accessible) way to do this. Let me know if you need more info/a video

**Comment by bbertucc** [comment]
@kevinandrews1 - pinged you in Slack. Hope you can setup a meeting with @wilsuriel03 to discuss this and other issues.

**Comment by kevinandrews1** [comment]
URLs, props, messages, none of these are keyboard accessible and as far as I can tell you have to use a mouse. This is actually critical. Can not launch without it. Cc @wilsuriel03 @bbertucc

**Comment by kevinandrews1** [comment]
I should confirm: This is when you're filtering. Could use radiobuttons (fieldset and legend_ for the list of URLs for instance to ensure semantic grouping. @wilsuriel03

**Comment by wilsuriel03** [comment]
This has been successfully fixed. @bbertucc . Feel free to retest @kevinandrews1

**Comment by bbertucc** [comment]
Re-assigning to @kevinandrews1  - looks great to me
