### ISSUE TITLE
Lack of Feedback When Creating Reports or Properties

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#358]
There is no feedback to inform users when actions such as creating a report or adding a property are successfully completed. For example, after adding a property, there is no communication indicating that the property has been successfully created. Clear feedback is crucial for users to know when their actions have been successfully completed. Without it, users may be unsure if their action was successful or if they need to retry. To address this, programmatically provide success messages using aria-live regions to announce updates to screen readers. For instance, after a report is created or a property is added, an aria-live="assertive" region can announce “Report successfully created” or “Property successfully added.” Additionally, move the focus to the success message once the action is completed to ensure users relying on screen readers are immediately notified of the success.

**Comment by wilsuriel03** [comment]
complete ✅

**Comment by kevinandrews1** [comment]
Hey @wilsuriel03 I get a 404 when trying to create a report so I'm unable to test that part. When I add a property now I know the properties page has loaded but it doesn't give any sort of indication the property was successfully added either through an on-screen message or solely through something like an ARIA alert to the screen reader.

**Comment by bbertucc** [comment]
> I get a 404 when trying to create a report

I created a separate issue, #361, with that note

**Comment by wilsuriel03** [comment]
both have been completed ✅

**Comment by kevinandrews1** [comment]
Creating a report, creating a property, and deleting a report don't communicate programmatically to the user that the action was successful--those are the three I tried @wilsuriel03.

**Comment by bbertucc** [comment]
@kevinandrews1 it eventually says "report deleted successfully" but it does take a while

@wilsuriel03 there might want to move up the component to read out sooner or use `aria-live="assertive"`

**Comment by bbertucc** [comment]
@wilsuriel03 here is more documentation: https://www.radix-ui.com/primitives/docs/components/toast

**Comment by kevinandrews1** [comment]
This makes way more sense, @bbertucc. I won't say rip out the toast because time. So, instead, @wilsuriel03, read this [piece on toasts](https://adrianroselli.com/2020/01/defining-toast-messages.html) by our good friend/mentor, Adrian, please.

**Comment by wilsuriel03** [comment]
@kevinandrews1 this should work now. I understand your concern about toast. I will see what I can come up for V2. For now this issue has been fix

**Comment by bbertucc** [comment]
Assigning @kevinandrews1 this to test.

**Comment by kevinandrews1** [comment]
On my call with @wilsuriel03 this afternoon I was not aware, for example, the report was deleted when we tested. @wilsuriel03 is going to do some more work--actually they mentioned making sure it merged with the latest branch.

**Comment by kevinandrews1** [comment]
Kicking this back to @wilsuriel03

**Comment by kevinandrews1** [comment]
Hey I jsut saw, in retesting #351 I didn't know when the account was deleted but saw I was back on login screen @wilsuriel03 not sure if it's related to the toasts issue.

**Comment by wilsuriel03** [comment]
@kevinandrews1 , I cant seem to recreate this issue. I have downloaded a screen reader and tested and I can hear the notification of the successful action.

**Comment by bbertucc** [comment]
@kevinandrews1 would you mind adding a video to confirm?

And @wilsuriel03 feel free to switch the assignee to Kevin or anyone else if you need something from them.

**Comment by kevinandrews1** [comment]
@wilsuriel03 I just tested creating and deleting reports and properties and it works but the issue boils down to the screen reader user not having an indication that action was successful. If there's a message on screen either about the asset being created or deleted, programmatically there's no communication of that message to the user. even on screen I check and manually and either it's quickly appearing and disappearing or it never appears. I would have something on screen for everyone regardless but also alert the user about the action. Here's the video you requested. Leaving this open for now: https://drive.google.com/file/d/1QkNcwdeOtgXSGYhCwEOW1JaMAFVnA1Wm/view?usp=sharing

**Comment by wilsuriel03** [comment]
I pushed another version, attempting to fix it. not sure why jaw screen reader isnt capturing it. @kevinandrews1

**Comment by kevinandrews1** [comment]
NO change @wilsuriel03 also on incognito here. Maybe give me a quick breakdown of what happens when a report and property is either created or deleted, what the implementation is, etc. I can do some research on this and try to figure out why JAWS isn't speaking it.

**Comment by bbertucc** [comment]
@wilsuriel03 and @kevinandrews1 I'm closing this issue in favor of #390 and #388 that should address this issue. Focusing on more discrete issues will allow us to better fix the problem.
