### ISSUE TITLE
Chart Bottom Goes Into Message Area

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#360]
I'm seeing the bottom of the chart hit the messages. 

Here is a video I've recorded to capture the issue: https://www.loom.com/share/8b5afc6c150244e096689e2d853241e0?sid=78a1bc5f-2780-4693-8d25-57443a767f7e

**Comment by wilsuriel03** [comment]
I can not replicate the  issue @bbertucc . what you tried different browsers and different reports?

**Comment by bbertucc** [comment]
It's an issue on Safari. See attached image

<img width="1270" alt="Screenshot of equalify reporting on safari with red arrows pointing to the issue" src="https://github.com/user-attachments/assets/98f49100-af10-4df7-9471-250cb9f5238d">

**Comment by bbertucc** [comment]
We isolated the problem to the max-height needing to be on a parent div during our contributor call

**Comment by wilsuriel03** [comment]
I made the change @bbertucc , do you mind retesting. Its hard for me to know if its working since I dont own macbook to test it. But doing it from my iphone in safari I dont see the issue.

**Comment by bbertucc** [comment]
Hmm.. I see the change, but it's still not working @wilsuriel03 

Have you tried testing in an emulator? [Perfecto](https://www.perfecto.io/free-trial?utm_term=trendemon) gives 240 minutes of free testing.

**Comment by wilsuriel03** [comment]
This is not working for me @bbertucc . I cant get Perfecto to work .

**Comment by bbertucc** [comment]
Hmm. Do you have any way to handle regression testing on Safari @wilsuriel03? We will need to support safari because a ton of users use it as their primary browser.

**Comment by bbertucc** [comment]
It's still not working @wilsuriel03 grr. The issue seems to be on Safari it's calculating the `max-height and SVG `viewbox` wrong.

Here's what I see on Safari, showing a ViewBox of `0 0 1056 598`:
<img width="338" alt="Screenshot 2024-07-23 at 3 23 44 PM" src="https://github.com/user-attachments/assets/6569fd9e-9068-4bb7-95b4-959eab4af94f">

Here's what I see on Chrome:
<img width="460" alt="Screenshot 2024-07-23 at 3 23 27 PM" src="https://github.com/user-attachments/assets/2d0043c1-277c-46bb-aaf5-e24967ef9af8">

**Comment by wilsuriel03** [comment]
its fixed @bbertucc , the deployment wasnt completed yet

**Comment by wilsuriel03** [comment]
feel free to retest

**Comment by wilsuriel03** [comment]
![image](https://github.com/user-attachments/assets/af81be68-8cf3-4731-bbb1-f198e366261f)

**Comment by bbertucc** [comment]
YESSS! You're a pro @wilsuriel03. Looks great!
