### ISSUE TITLE
Make Production Live at dashboard.equalify.app and api.equalify.app

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#367]
Equalify is currently published at `equalify.dev` and `api.equalify.dev`. To stay consistent, let's make production `dashboard.equalify.app` and `api.equalify.app`.

**Comment by bbertucc** [comment]
@heythisischris let me know if you need me to do anything for you here.

**Comment by bbertucc** [comment]
We might also consider turning `equalify.dev` and `api.equalify.dev` into the staging URLs, but I leave that up to you all.

**Comment by heythisischris** [comment]
Done!

**Comment by bbertucc** [comment]
Looks great @heythisischris!
