### ISSUE TITLE
 scan.equalify.app needs a development branch and a production branch

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#368]
Main goes to production and `dev` or `staging` would be for development stuff

**Comment by bbertucc** [comment]
@azdak looks like you've set the stage for it. Let me know when this is complete.

**Comment by azdak** [comment]
This is actually done- scan-dev.equalify.app is up and running and connected to `dev`- but the old dev endpoints are still up on production, pending #362

**Comment by bbertucc** [comment]
Tested and looks great!
