### ISSUE TITLE
Unable to run "Scan all pages"

### ISSUE THREAD

**Issue by alphex** [bbertucc/equalify#38]
On this screen : https://equalify.lndo.site/index.php?view=scans
(I'm using Lando to host it locally)

```
Warning: Undefined variable $records in /app/models/db.php on line 397 Fatal error: Uncaught Exception: 
Cannot insert scan with status "running" and records "" in /app/models/db.php:397 Stack trace: #0 
/app/actions/scan_all_pages.php(28): DataAccess::add_scan('running', 'a:2504:{i:0;a:1...') #1 {main} thrown 
in /app/models/db.php on line 397
```

This suggests that it can't connect to SQL?

But I was able to add a site, that generates a list of pages to scan.

![screenshot_2022-05-19_at_14_17_39](https://user-images.githubusercontent.com/597641/169372131-c0c582ab-744f-4706-bf46-c762e93f3f80.png)

Unsure how to fix.
Thanks

**Comment by bbertucc** [comment]
Hi @alphex- What version of PHP are you using? The app requires PHP 8 and above.

**Comment by alphex** [comment]
PHP 8.0.18 (cli) (built: Apr 20 2022 16:33:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.18, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.18, Copyright (c), by Zend Technologies

**Comment by alphex** [comment]
```


system | Linux 580f73334858 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64
-- | --
Build Date | Apr 20 2022 16:33:17
Build System | Linux 7652d3749aea 5.13.0-1021-oracle #26~20.04.1-Ubuntu SMP Mon Mar 7 14:30:17 UTC 2022 aarch64 GNU/Linux
Configure Command | './configure' '--build=aarch64-linux-gnu' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-iconv' '--with-openssl' '--with-readline' '--with-zlib' '--disable-phpdbg' '--with-pear' '--with-libdir=lib/aarch64-linux-gnu' '--disable-cgi' '--with-apxs2' 'build_alias=aarch64-linux-gnu'
Server API | Apache 2.0 Handler
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /usr/local/etc/php
Loaded Configuration File | (none)
Scan this dir for additional .ini files | /usr/local/etc/php/conf.d
Additional .ini files parsed | /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini, /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini, /usr/local/etc/php/conf.d/docker-php-ext-bz2.ini, /usr/local/etc/php/conf.d/docker-php-ext-calendar.ini, /usr/local/etc/php/conf.d/docker-php-ext-exif.ini, /usr/local/etc/php/conf.d/docker-php-ext-gd.ini, /usr/local/etc/php/conf.d/docker-php-ext-gettext.ini, /usr/local/etc/php/conf.d/docker-php-ext-imagick.ini, /usr/local/etc/php/conf.d/docker-php-ext-imap.ini, /usr/local/etc/php/conf.d/docker-php-ext-intl.ini, /usr/local/etc/php/conf.d/docker-php-ext-ldap.ini, /usr/local/etc/php/conf.d/docker-php-ext-memcached.ini, /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini, /usr/local/etc/php/conf.d/docker-php-ext-oauth.ini, /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini, /usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini, /usr/local/etc/php/conf.d/docker-php-ext-redis.ini, /usr/local/etc/php/conf.d/docker-php-ext-soap.ini, /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini, /usr/local/etc/php/conf.d/docker-php-ext-zip.ini, /usr/local/etc/php/conf.d/xxx-lando-default.ini
PHP API | 20200930
PHP Extension | 20200930
Zend Extension | 420200930
Zend Extension Build | API420200930,NTS
PHP Extension Build | API20200930,NTS
Debug Build | no
Thread Safety | disabled
Zend Signal Handling | enabled
Zend Memory Manager | enabled
Zend Multibyte Support | provided by mbstring
IPv6 Support | enabled
DTrace Support | disabled
Registered PHP Streams | https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters | zlib.*, convert.iconv.*, bzip2.*, string.rot13, string.toupper, string.tolower, convert.*, consumed, dechunk
```

![screenshot_2022-05-19_at_21_40_15](https://user-images.githubusercontent.com/597641/169431544-f891913f-ef73-4c0c-8357-e165e938667d.png)

**Comment by bbertucc** [comment]
@alphex 

If the "Single Page" option under "add site" works, you might need to install XML-RPC since it was [not added by default in PHP 8](https://php.watch/versions/8.0/xmlrpc). XML-RPC is required to do the XML magic.

I also added issue #40. A Docker container should take care of future issues like this one, but it may cause more headaches than it's worth. Curious what you think.

**Comment by alphex** [comment]
I will try installing XML-RPC, thanks!

I'll leave this open until I can try and get it working later this week.

Once I get it working, I'll gladly share my lando configuration back to this project.

**Comment by alphex** [comment]
@bbertucc 
Still getting the same error.  

XMLRPC is installed now

![screenshot_2022-05-24_at_09_18_13](https://user-images.githubusercontent.com/597641/170044425-e3936e9a-54aa-45c8-9e84-791b2e9906fe.png)

```
Warning: Undefined variable $records in /app/models/db.php on line 397 Fatal error: Uncaught Exception: Cannot insert scan with status "running" and records "" in /app/models/db.php:397 Stack trace: #0 /app/actions/scan_all_pages.php(28): DataAccess::add_scan('running', 'a:2504:{i:0;a:1...') #1 {main} thrown in /app/models/db.php on line 397
```

I even destroyed the application and rebuilt it, just in case... same error.

Thoughts?

Thanks!

**Comment by bbertucc** [comment]
Hmm @alphex - looking again at your phpinfo, looks like you also need XMLReader, XMLWriter, and XML.
Those extensions ship with PHP source, so they SHOULD be active unless you disabled them. 

Here's a PHP info file that you can try to replicate: https://demo.equalify.app/info.php

I'll also invite you to our "super secret" demo, so you can try out a working example.

**Comment by alphex** [comment]
Ummm, ok, all of those are enabled.

![screenshot_2022-05-24_at_10_03_57](https://user-images.githubusercontent.com/597641/170054804-1d9d5e5e-f4c1-407b-8746-562cc71c390c.png)

I will deep dive your PHPINFO dump later today.

Thanks!

**Comment by bbertucc** [comment]
Hi @alphex - Are you still having the issue with the server? We just published a new release.

**Comment by alphex** [comment]
I haven't checked in a bit, I will give this a review this weekend!

**Comment by bbertucc** [comment]
This should be fixed with our latest release.
