### ISSUE TITLE
404 After Signup

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#381]
Looks like I'm getting a 404 when logging in after signing up. Here's a video: https://www.loom.com/share/178493b7875049faada8cebbfcb9a360?sid=44ff554e-73eb-4733-bda6-385b9e9307b7

**Comment by heythisischris** [comment]
It's a CORS issue! We were stuck using the old API endpoint `api.equalify.dev` instead of the new API endpoint `api.equalify.app`.

I updated the production/staging env.
