### ISSUE TITLE
Send to Scan Stays active and has no feedback, causing multiple scans to be sent

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#385]
When submitting a scan, we don't know if the scan is submitted. This a big deal because it sometimes takes several seconds to send to the scan and leads to multiple submissions.

Here's an example of how I've done this on other versions: https://www.loom.com/share/31ba2644145a4942a6cac8fdff1e9e7b?sid=5353837d-474d-4dcb-83eb-f8fec849a1b7

**Comment by wilsuriel03** [comment]
complete ✅

**Comment by bbertucc** [comment]
Looks great @wilsuriel03!
