### ISSUE TITLE
Property `sitemapUrl` confuses people

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#393]
Adding and updating properties requires the `sitemapUrl` field, and getting single and multiple properties displays that same field.

That's confusing. Properties should instead get and output have a `url` or `propertyURL` because they aren't only sitemaps.

**Comment by heythisischris** [comment]
As commented in #392, the attribute name was already renamed from `sitemapUrl` to `propertyUrl`. Postman documentation is updated as well. No more confusion!

**Comment by bbertucc** [comment]
Tested and works.
