### ISSUE TITLE
Remove filter button is not accessible

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#399]
There is no way to tab to individual filters and remove each filter.

**Comment by wilsuriel03** [comment]
working on it

**Comment by wilsuriel03** [comment]
complete ✅

**Comment by bbertucc** [comment]
Adding @kevinandrews1 to this to test to make sure he can remove a filter.

**Comment by kevinandrews1** [comment]
@bbertucc @wilsuriel03 I can remove a filter which was the specific issue at hand. The experience is not great with a screen reader--you hear the message the filter was removed along with a bunch of other extraneous stuff on the page spat out at you--but it can be done. That being said I'd hate for this alone to hold up the JS version launch. Here's a [video](https://drive.google.com/file/d/1ZLrB3cPnA3Zj3P9UGyEFzO_llwFHCZ0W/view?usp=drive_link). I'll close it and we can always reopen it. It's something we should fix but functionally it does work. Happy to be overruled if y'all want to prioritize it. These are also judgment calls at the end of the day but I think it should go into a separate issue where the experience gets cleaned up.

**Comment by wilsuriel03** [comment]
@kevinandrews1 Regarding the extraneous information when removing filters, the long filter names are read out loud by the screen reader, which can seem verbose but is necessary to clearly communicate which filter was removed. This is a trade-off to ensure clarity for all users. its not "Extraneous stuff"
