### ISSUE TITLE
Continued A11y Maintence Until September

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#400]
## Overview
@kevinandrews1 is providing accessibility feedback where needed. 

@bbertucc agreed to pay $90/hr until September when we'll review the progress. (I hope we can turn this into a flat rate cost as we figure out our cadence.

Any additional feedback can be added to this issue.

## Agreed Timeline
The following can be crossed off when invoices are paid:
- [x] July 2024
- [x] August 2024
- [x] September 2024

**Comment by kevinandrews1** [comment]
July's a11y hasn't been paid yet @bbertucc. Todo today for me is to:

- [x] Add up the hours worked in July
- [x] Create the invoice for July's work
- [x] Send the invoice
- [ ] Continue tracking the hours in August

**Comment by kevinandrews1** [comment]
Just invoiced for July @bbertucc and emailed you the PDF. $765.00 for 8.5 hours. I did not get super granular just gave an overall summary of the work and listed the time blocks worked. Let me know if you prefer a different format.

**Comment by bbertucc** [comment]
@kevinandrews1 paid

**Comment by bbertucc** [comment]
Note: We're going to explore flat rate after August, as discussed with @kevinandrews1 today.

**Comment by bbertucc** [comment]
Closing this in favor of our handbook issue update that basically gives @kevinandrews1 free range https://github.com/EqualifyEverything/handbook?tab=readme-ov-file#how-are-bounties-budgeted
