### ISSUE TITLE
[Monitor] Detect dynamic pages/SPAs

### ISSUE THREAD

**Issue by azdak** [bbertucc/equalify#402]
The Monitor system is based on historical comparisons of raw HTML responses- for SPAs or pages using js frameworks like React/Angular/Svelte, content changes may not be detected. We should develop a heuristic to test for the most common of these frameworks, and include a warning/flag in results for pages where they're detected.

**Comment by bbertucc** [comment]
Contributor Call Update: @azdak is aiming to knock this out this week.

**Comment by bbertucc** [comment]
This is done. Here is an example: https://monitor-dashboard.equalify.app/monitor/667ed3c76e2226011bba2e8c

Monitor will alert if there is a SPA detected. SPAs need to be alerted because change management is handled differently.
