### ISSUE TITLE
[Monitor] Wireframe Frontend Integration

### ISSUE THREAD

**Issue by azdak** [bbertucc/equalify#403]
### Overview
To integrate Monitor into the main app, we need to develop a UX integration that's intuitive and simple for users to understand. To that end, we should develop wireframes or a functional test based on the current Dashboard UI prior to API integration.

### User Workflow
The core of the expected user workflow is:
- Users enable Monitor (for a page, perhaps also for a property?)
- The user is notified when a change to a page is detected
- A full scan is also triggered when a change is detected, and this is communicated to the user

### Deliverable
The wireframes or a functional test should include the following:
- Communicating to the user what Monitor does, and its limitations
- Adding/Enabling Monitor for pages
- Setting Monitor sensitivity and check period
- Displaying the Monitor status of each page in the dashboard (enabled, last check, etc)
- Displaying historical Monitor data for individual pages (see [the monitor dashboard](https://monitor-dashboard.equalify.app/))

**Comment by bbertucc** [comment]
Today we're looking at comps for V2, and will discuss how to fold Monitor into those designs.

**Comment by bbertucc** [comment]
Do you think you can bring Monitor into the Version 2 Mockups by Monday (9/9) @wilsuriel03?

**Comment by bbertucc** [comment]
Contributor call updates: V2 mockups will include Monitor. Aiming for September 16.

**Comment by bbertucc** [comment]
@azdak is this complete with @wilsuriel03 mockups?
