### ISSUE TITLE
User Verfiication Email not sent after fixing a form input

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#414]
To recreate:

1. I added information of a user that already exists
2. I updated my information to a new user. Form said " verification code has been sent to your email."
3. No email was received.

**Comment by wilsuriel03** [comment]
@bbertucc, could you please provide clarification? Did this occur on the sign-up page? After entering existing user credentials in the form, did you submit it and encounter an error? Subsequently, when you went back, updated the fields with new user credentials, did you not receive an email?

**Comment by bbertucc** [comment]
I'm still getting an issue. Try this:

1. Add email of a user that already exists (for instance, you can try `blake@bertuccelli-booth.org`).
2. Click "Continue". You should receive the error `User already exists`.
3. Now add a new email and click "continue"

Did you get a verification email? I'm not.

-Bb.

**Comment by wilsuriel03** [comment]
@bbertucc , I will push my changes soon to another issue related to this, but yes I was getting a verification email after updating the email to a new one. I will ping you when the PR is up.

**Comment by bbertucc** [comment]
Cool. I'm going to close this issue. I'll open it again if more people report it.
