### ISSUE TITLE
[Dashboard] Reports page "Active Issues:" count is inaccurate

### ISSUE THREAD

**Issue by azdak** [bbertucc/equalify#425]
The reports listing page (https://dashboard.equalify.app/reports) shows an "Active Issues:" count for each report, but this count is of **all** issues for the property, not the (correct) number of filtered issues in the report. We should remove it for now.

**Comment by azdak** [comment]
Opened a PR https://github.com/EqualifyEverything/equalify-dashboard/pull/44

**Comment by wilsuriel03** [comment]
merged PR into staging, we can close this issue for now @azdak
