### ISSUE TITLE
Add Property "Send to Scan" button generates Warning error

### ISSUE THREAD

**Issue by joelhsmith** [bbertucc/equalify#436]
When I added a new Property for the first time and hit "Send to Scan" I get an error: 

<br /> <b>Warning</b>: Array to string conversion in <b>/workspace/actions/process_property.php</b> on line <b>173</b><br /> 2024-08-16 18:26:06: Array

[Warning error message screenshot](https://github.com/EqualifyEverything/handbook)

**Comment by bbertucc** [comment]
@joelhsmith - we're just transitioning to our version 1, where these issues have been taken care of. sending you the updated login form momentarily!

**Comment by joelhsmith** [comment]
No prob! I'm just noodling around.
