### ISSUE TITLE
System Adds a Trailing Slash after Validating a sitemap url

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#437]
1. Added in this url: `https://financialaid.duke.edu/sitemap/sitemap-0.xml`
2. Saved property
3. When I came back to the property, it had a trailing slash like this: `https://financialaid.duke.edu/sitemap/sitemap-0.xml/`

**Comment by bbertucc** [comment]
Hey @heythisischris this looks like an API issue.

**Comment by heythisischris** [comment]
Fixed with https://github.com/EqualifyEverything/equalify-api/commit/3a391852c0e5f596366967bd7eb66eb9e96cffc8
