### ISSUE TITLE
Scan Data on Dashboard/API is not the Same as Scan Data in Equalify

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#438]
Checkout this video: https://www.loom.com/share/90eda2fad5984969a7e4cff4e21ab72e?sid=bdbe5734-1357-4dd6-ae6a-1524c229e4f2

Also attaching scan data of `https://financialaid.duke.edu/search` from scan.equalify.app and data from dashbaord.equalify.app

Tagging this Milestone "Version 1" because we shouldn't start uploading client data until this is resolved.

[equalify-dashboard-results.json](https://github.com/user-attachments/files/16641012/equalify-dashboard-results.json)
[equalify-scan-results.json](https://github.com/user-attachments/files/16641013/equalify-scan-results.json)

**Comment by heythisischris** [comment]
@bbertucc Fixed with https://github.com/EqualifyEverything/equalify-api/commit/ce9c341cf2f50daadaab9f089f487d38f2feda74
![image](https://github.com/user-attachments/assets/bd5504b1-e1ac-456e-b118-4ef9fd906d0d)
