### ISSUE TITLE
URLs are Being Scanned, but Not Showing up on report - and Messages missing from some pages

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#439]
Seeing over 20 URLs when scanning sitemap for `https://equalify.app`, but only 10 show up.

Also, messages are missing from some page lists.

Video: https://www.loom.com/share/68e5b2748995401d95e4391096c91d3e

**Comment by heythisischris** [comment]
Think I've got it fixed with this commit: https://github.com/EqualifyEverything/equalify-api/commit/36aafaa84bc415b05f169c4feecee3d4cc1cd2fa

![image](https://github.com/user-attachments/assets/c42256d5-70a5-40b0-a7a1-56d6bb56604f)

**Comment by bbertucc** [comment]
Looks good!
