### ISSUE TITLE
Prioritize Scans Based On Clients

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#444]
Add a system that fairly distributes scans, so one client who requests 100k doesn't jam our scan.

**Comment by bbertucc** [comment]
I have to test this.

**Comment by bbertucc** [comment]
Worked great @azdak - Can we push to prod?

**Comment by azdak** [comment]
Yeah I can go ahead and add this to the prod scan- tho we want to keep
cognizant of that trial for BullMQ Pro running out in like the next week or
so

**Comment by bbertucc** [comment]
I just bought the annual plan @azdak and Slacked you the key
