### ISSUE TITLE
Deleting Account Causes Bugs

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#452]
## Issue
When re-adding a user that was already added, the following errors occurred:
- Correct verification code returns the error: `PostConfirmation failed with error duplicate key value violates unique constraint "users_email_key".` and `User cannot be confirmed. Current status is CONFIRMED`
- if you bypass the verification by revisiting dashboard in a private browser window, the API key does not appear
- adding a property or report leads to a 404.

## To recreate:

1. Create a user
2. add a property for that user
3. delete the user
4. Signup with the same info of the user you deleted
5. Enter verification code
6. Verification code shows various errors including `PostConfirmation failed with error duplicate key value violates unique constraint "users_email_key".` and `User cannot be confirmed. Current status is CONFIRMED`
7. Visit dashboard in a private browsing window - you should be able to login now
8. Visit the account page and you'll see that no API key exists
9. try adding a property, and you'll be taken to a 404 page.

## Expected result
Deleting a user deletes the user and all information related to it. Adding a new user adds a user with information as expected.

**Comment by heythisischris** [comment]
@bbertucc Taken care of in the following commits:
Frontend → https://github.com/EqualifyEverything/equalify-dashboard/commit/3a7ad0b8169d81c2f50c86ead9f59ca8b94d77ae
Backend → https://github.com/EqualifyEverything/equalify-api/commit/2f86d3a20aadc1c64bd8e8a96ffb8c91a5bd7e0e

I added a new API endpoint called `/delete/user` which is called right before deleting a user from Cognito. This API request deletes all user data from our database. After this succeeds, we proceed to delete the user from the Cognito user pool.

This prevents the duplicate email unique key issue you mentioned above, and it also ensures all user data associated with a given account is actually purged.

**Comment by bbertucc** [comment]
Hmm. @heythisischris I just tried deleting `blake@philosophers.group`. When I recreate a user with the same email, I'm still getting `PostConfirmation failed with error duplicate key value violates unique constraint "users_email_key".` and `User cannot be confirmed. Current status is CONFIRMED`

**Comment by heythisischris** [comment]
@bbertucc Oh, that's because those users were created before this endpoint was added.

You created `blake@philosophers.group` on `2024-08-23` and that entry wasn't deleted on the DB.

Just manually reconciled all previously deleted users, you should be good to go now.

**Comment by bbertucc** [comment]
Cool. Works. Closing.
