### ISSUE TITLE
Document Delete User API Endpoint

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#453]
This is undocumented in Postman: https://github.com/EqualifyEverything/equalify-api/commit/2f86d3a20aadc1c64bd8e8a96ffb8c91a5bd7e0e

@heythisischris added a new API endpoint called `/delete/user` which is called right before deleting a user from Cognito. This API request deletes all user data from our database. After this succeeds, we proceed to delete the user from the Cognito user pool.

**Comment by heythisischris** [comment]
Added to the Postman Collection: https://documenter.getpostman.com/view/26880150/2sA3BoarvB#e45f7420-ad83-477e-857b-c9c992e37969

**Comment by heythisischris** [comment]
Also, I moved our Postman Collection to an Equalify subdomain: https://docs.equalify.app/

**Comment by bbertucc** [comment]
Great! Added a link to it in the footer of http://equalify.app
