### ISSUE TITLE
SSO and SCIM Integrations for Enterprise Customers

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#458]
During a demo today, the need for SSO and SCIM came up. The organization needs IT to be able to provision users. Not having SSO and SCIM would be a blocker for the organization. We might want to consider integrating them into our core product.

**Comment by bbertucc** [comment]
Just going to tag this API for now..

**Comment by alexstine** [comment]
@bbertucc There may be an AWS solution here but I never could understand SSO well enough to provide any guidance.

https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html

A little bit more info might be useful such as which SSO solutions they need to integrate with.

**Comment by bbertucc** [comment]
Thanks @alexstine. I'll get some more info on that. This is not an immediate issue, but definitely wanted to post it for any ideas that pop up. They are expecting that this would be an add-on to our existing service.

**Comment by bbertucc** [comment]
Closing this as we wait for a customer who actually requests it.
