### ISSUE TITLE
Send Single Page to Scan Not Working

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#459]
Sending a page to scan doesn't seem to send it to the scan.

**Comment by heythisischris** [comment]
https://github.com/EqualifyEverything/equalify-api/commit/f7b73b79058f1e8cd47b334b35ad87b12e95aab8

@bbertucc Created a commit to fast-track single URL scans, this seems to fix the issue. Sitemaps will still be queued in our 15 minutes processScans cronjob.

Just tested out single and sitemap scans with https://equalify.app on production, both work well.

![image](https://github.com/user-attachments/assets/62a66b16-a787-40f5-acb0-cf82a63c9d97)
![image](https://github.com/user-attachments/assets/85050ba2-276c-4848-80f8-ed17f44339a2)

**Comment by bbertucc** [comment]
@bbertucc is going to test. it's updated on production.

**Comment by bbertucc** [comment]
@heythisischris i'm not seeing this working on prod or staging? I see it loading now, but I don't see the scan actually reflected in the "Scans" list.
