### ISSUE TITLE
Supress Landmark and Empty Alt Tag Rules that already bring up violations

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#472]
Several landmark issues are showing more than once (see [results.json](https://github.com/user-attachments/files/17135326/results.json)) because axe both reports on rule violations and gives a violation message.

For instance, that JSON shows the message:
> Landmark No Duplicate Banner Rule: Ensure the document has at most one banner landmark. Document should not have more than one banner landmark. More information: https://dequeuniversity.com/rules/axe/4.10/landmark-no-duplicate-banner?application=axe-puppeteer

> Document has more than one banner landmark

There is no need for those duplicates. We can just do the basic mesages

Here are other duplicates that can be surpressed:
- Landmark No Duplicate Contentinfo Rule: Ensure the document has at most one contentinfo landmark. Document should not have more than one contentinfo landmark. More information: https://dequeuniversity.com/rules/axe/4.10/landmark-no-duplicate-contentinfo?application=axe-puppeteer
- Landmark No Duplicate Banner Rule: Ensure the document has at most one banner landmark. Document should not have more than one banner landmark. More information: https://dequeuniversity.com/rules/axe/4.10/landmark-no-duplicate-banner?application=axe-puppeteer	
- Landmark Banner Is Top Level Rule: Ensure the banner landmark is at top level. Banner landmark should not be contained in another landmark. More information: https://dequeuniversity.com/rules/axe/4.10/landmark-banner-is-top-level?application=axe-puppeteer
- Landmark Contentinfo Is Top Level Rule: Ensure the contentinfo landmark is at top level. Contentinfo landmark should not be contained in another landmark. More information: https://dequeuniversity.com/rules/axe/4.10/landmark-contentinfo-is-top-level?application=axe-puppeteer
- Landmark Unique Rule: Ensure landmarks are unique. Landmarks should have a unique role or role/label/title (i.e. accessible name) combination. More information: https://dequeuniversity.com/rules/axe/4.10/landmark-unique?application=axe-puppeteer

To test, scanning [https://wordpress.org/five-for-the-future/testimonials/](https://wordpress.org/five-for-the-future/testimonials/) should give all the related landmark rules

**Comment by azdak** [comment]
What I think is happening is that axe has `Rules`, which are collections of `Checks`, and if one of a rule's checks fails, then the rule itself fails. When either a rule **or** a check fails, a message is generated describing it- which makes sense, in the case of rules that contain like 5 checks, you'd want to know what _specifically_ is causing the parent `Rule` to fail. But in the case (for example) of `landmark-no-duplicate-banner`, the Rule contains only **one** Check, and axe returns the messages for both the Check failing, and its parent Rule failing, which seems to be a duplicate. 

We could figure out a way to manually suppress Check messages just for these Rules, but (besides being kinda an ugly fix) the issue will obviously still be there for any Rules that only contain a single check. 

This to me points to more a presentation/information architecture issue- the way we're presenting it is that scanned pages return **messages for each violation**, but (best I can tell) the way axe _actually_ works is that scans return **nodes with detected violations**, and then attaches multiple **messages** (including "check" messages) to those nodes, to describe the violations. So I kinda think this would be fixed if the presentation was more "nodes->messages attached to nodes" than the way we're doing it, which is a table of messages.

**Comment by bbertucc** [comment]
I can't quite understand the architecture update @azdak. How would you express that in the update to the schema?

**Comment by bbertucc** [comment]
Closing this in favor of #475
