### ISSUE TITLE
YouTube Video Stuck Scanning

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#473]
A youtube video url is stuck in the active scan and it appears that that is limiting the number of scans that can be run concurrently 
![Screenshot 2024-09-25 at 10 38 51 AM](https://github.com/user-attachments/assets/bf115001-4353-48ca-97f7-ff27b4a8225f)

**Comment by azdak** [comment]
I've restarted the Redis server, which looks to have fixed this (I've also added some stuff to the docs around restarts). Not 100% sure what happened here, but that url (https://www.youtube.com/intl/ALL_mx/ads/resources/creative-directory/) actually resolves to a different domain/site, with what looks like a _bunch_ of redirects. I suspect something happened with the worker/timeout error handling, but unless it recurs will be tough to pin down.

**Comment by bbertucc** [comment]
All good. Closing issue.
