### ISSUE TITLE
General Project Management (November)

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#488]
## Overview
This is an issue to cover general project management. That includes handbook development, meeting management, and updates.

## Estimates
Each estimate will be marked done when paid.
- [x] November: 20 hours.

## Bountied
Since this is a bountied issue, Assignees should post an estimate that is then approved as per this note in the handbook: https://github.com/EqualifyEverything/handbook?tab=readme-ov-file#how-are-bounties-budgeted

**Comment by bbertucc** [comment]
@azdak @heythisischris @kevinandrews1 @wilsuriel03 can you approve/squash this? It feels weird approving my own issue.

**Comment by heythisischris** [comment]
@bbertucc Vote of approval here!

**Comment by bbertucc** [comment]
Looks like I hit 16.5 hours this month.
