### ISSUE TITLE
Add support for including URL parameters in a given scan

### ISSUE THREAD

**Issue by heythisischris** [bbertucc/equalify#498]
It looks like we need to add support for scanning URLs with the query parameter included (i.e. https://equalify.app/cart?item=1).

Per Gen Herres on December 1st, 2024:
> I’m back and with more requests.
URL parameters: it looks like this needs to be something inside of Equalify to be added.
The goal: be able to get monitored a URL like https://easya11yguide.com/cart/?add-to-cart=909 — this allows us to check the cart when an item is actually in it. Which is far more useful than checking an empty cart.
I tried creating a property with this sitemap, which includes a URL with a parameter: https://easya11yguide.com/test-sitemap.xml
But when Equalify ran the scan, it removed the url parameter.
The goal here is creating a custom XML sitemap where I can add products of different types to the cart, and also view the checkout page and even the order confirmation page and have them all checked by Equalify.
If you want me to create an issue on Github, just let me know. A quick search there didn’t show anything related to this.

**Comment by bbertucc** [comment]
Thanks. Is this a scan or API issue? Tagging @azdak. This issue seems in scope of what we should be working on now, so I would encourage it be budgeted.

**Comment by azdak** [comment]
So just had a look at the code again and ran a couple of tests, and can't reproduce- on both single pages and sitemaps query strings are retained:
![Screenshot_20241202-105214](https://github.com/user-attachments/assets/3f462470-e6d4-44f6-ac2e-b6999483ea70)

In this case the page itself redirects the URL to https://easya11yguide.com/cart/, so when the actual browser scan is run, that's the URL in the data (tho it looks like the page is consuming the parameters to populate the cart on the redirect page, so those parameter-specific cart items should be being scanned/reflected in the scan data).
