### ISSUE TITLE
Set Requirements for Manual Testing

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#499]
## Problem
We need Manual Testing!

## Process to Close Issue
- [x] @kevinandrews1 will budget the first three steps, and tag @bbertucc for approval on commented budget. (Note: This will be billed at a $70/hour rate since it's not accessibility testing.)
- [x] @kevinandrews1 will review #297 and meet Raga to discuss updated requirements.
- [x] @kevinandrews1 will post a new issue with those requirements, then we can mark this issue done.

## Notes
- On the issue that @kevinandrews1 posts, @azdak and @heythisischris will the review issue to add technical notes on interacting with the API
- @bbertucc will add final notes on the product relationship
- @wilsuriel03 will add any additional questions and budget for buildout, which will be reviewed by @bbertucc

**Comment by bbertucc** [comment]
As noted in https://github.com/EqualifyEverything/equalify/issues/441#issuecomment-2515690404, I'll be paying close attention to the budget @wilsuriel03 submits. The last few budgets @wilsuriel03 put forward were quite a bit higher than I have seen in my web design experience.

**Comment by wilsuriel03** [comment]
@bbertucc , I want to address your comment here. While I appreciate the need to keep a close eye on budgets, I want to clarify that my submissions are always based on the scope of work, time required, and the expertise I bring—not arbitrary figures. I’ve approached each task with fairness and transparency, ensuring the pricing reflects the value provided.

As you noted in #441, the LA311 project was approved at $2,750, and I delivered everything agreed upon within that budget. This type of work goes beyond just design—it involves research, accessibility considerations, and ensuring that what’s delivered aligns with both client needs and Equalify’s mission.

I understand that Equalify’s finances require careful management, and I respect your role in approving or adjusting budgets to fit the project’s goals. However, comments like these, especially when publicly stated, don’t reflect well on either of us. They could unintentionally imply I’m being unreasonable, which isn’t the case. Perhaps we could consider exploring the option of bringing in an accountant or financial manager to help balance priorities and resource allocation moving forward.

I’m committed to contributing my best work, but I also want to ensure our collaboration is built on mutual respect and clear communication. Let me know how I can help ensure we’re aligned moving forward.

**Comment by bbertucc** [comment]
Respect your need for private communication @wilsuriel03. Radical transparency is a key aspect of all my work, and why I'm focused on Accessibility. I appreciate that only some people share my interests. Radical transparency has been a deal killer with previous collaborators. There are many other projects that you could work on that would be more filtered. Here's one you might be interested in: https://testparty.ai/careers

**Comment by bbertucc** [comment]
@kevinandrews1 is meeting with Lucy

**Comment by kevinandrews1** [comment]
@bbertucc I just submitted #509.

**Comment by bbertucc** [comment]
Thanks @kevinandrews1. Closing this and will post on #509
