### ISSUE TITLE
WAVE by WebAIM

### ISSUE THREAD

**Issue by jrchamp** [bbertucc/equalify#5]
The Little Forrest reports weren't loading for me at all. I have to assume it's because I don't have an account with them.

An external, but free (and working) alternative would be `https://wave.webaim.org/report#/<url minus scheme>`

**Comment by bbertucc** [comment]
Little Forrest's API server crashed (maybe due to this plugin's popularity 😉  ). I'm not using WebAIM because they charge for API queries. That said, my next version will include an option to choose the service you want. Adding WebAIM to my list of integrated (#2).

**Comment by bbertucc** [comment]
@jrchamp - LF settings is back up. FYI.
