### ISSUE TITLE
Really verbose screen reader output after pressing suggest issue

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#502]
@heythisischris, please see the [video](https://drive.google.com/file/d/1D05guAoirxlNylMoSqI58L-VYYU05x8X/view?usp=sharing) I created for context. After pressing Suggest Issue the experience is really verbose because JAWS reads out the page title. The page title is the what appears to be the entire Axe rule. That is crazy.

**Comment by heythisischris** [comment]
Taken care of! Here's the commit: https://github.com/EqualifyEverything/equalify-dashboard/commit/31fadcc39c402c860a1c96f48a2c87823769efe4

**Comment by bbertucc** [comment]
Thanks @heythisischris! Assigning to @kevinandrews1 to validate.
