### ISSUE TITLE
Entire contents of llm modal is read out at once

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#503]
The contents of the modal get read out. I recommend setting programmatic focus on the h1 and the title of the modal should reflect this. Right now the page title is the Axe rule. (The h2 you can style however you like but I don't particularly see the purpose of making that a heading).

**Comment by heythisischris** [comment]
Taken care of! Here's the commit: https://github.com/EqualifyEverything/equalify-dashboard/commit/31fadcc39c402c860a1c96f48a2c87823769efe4

**Comment by bbertucc** [comment]
Thanks @heythisischris! Assigning @kevinandrews1 to validate.
