### ISSUE TITLE
Confusing reading order in llm modal

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#504]
I would move the close button to be immediately after the h2 and inject the AI response after the close button. Currently the user has to go backward (up arrow) through the reading order which is unintuitive.

**Comment by heythisischris** [comment]
Taken care of! Here's the commit: https://github.com/EqualifyEverything/equalify-dashboard/commit/c52c9362c288a20de7be134e420315ffa4903531

**Comment by bbertucc** [comment]
Thanks @heythisischris! Assigning @kevinandrews1 to validate.
