### ISSUE TITLE
No screen reader updates in llm modal

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#505]
Currently there is no update for screen readers alerting them that the AI response is done generating. I recommend having the eta 1 minute... text using the status role and when the response is generated the text could indicate the response has been generated, also with the status role.

**Comment by heythisischris** [comment]
Taken care of! Here is the commit: https://github.com/EqualifyEverything/equalify-dashboard/commit/af30be52acc1f2d43c92d21db9ddd0b69b99519a

**Comment by bbertucc** [comment]
Thanks @heythisischris! Assigning @kevinandrews1 to validate.
