### ISSUE TITLE
Project Raga for Manual testing

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#509]
### Description

As a user, I'd like to be able to directly submit test data to Equalify. This would allow me to:

- Share insights
- Track trends
- Collaborate with others

### Proposed Solution

To achieve this, we'll develop a Chrome extension that will:

- Capture accessibility issues
- Efficiently test with screen readers

### Key Considerations

- Integration with existing tools
- Automation capabilities
- User-friendly interface
- Scalability

### Next Steps

- Budget the project
    - Initial development: $X (tbd)
    - Lucy's consultation: $70 (via Amazon or cash)
    - Kevin's consultation: $555 (just under eight hours: an hour with Lucy on 12/16, an hour meeting tbd with @heythisischris and @azdak within the next couple of weeks, a buffer of three hours for general UX/usability work, and up to three hours to meet with others for guerilla UX to gather feedback)
    - Comp up to three other people for their time and feedback: $210 ($70 per hour session, prioritizing disabled a11y pros/devs)
    - Total so far: $835
- Define requirements
 - Get technical specs from @heythisischris and @azdak
- Approval from @bbertucc
### Community Survey

We'll conduct a survey among developers primarily as well as accessibility professionals to gather information about their current testing practices and preferences. Key questions include:

- What automation tools are you currently using for accessibility testing?
- What are the biggest challenges you face when testing accessibility?
- What features would you like to see in an accessibility testing tool?

### Additional Notes

- Consider challenges of testing password-protected sites.
- Automate repetitive testing tasks.
- Gather user feedback.

**Comment by bbertucc** [comment]
@kevinandrews1 is the community survey budgeted? I see an overview of that, but I don't see it in the budget.

Three people doesn't seem like a bit enough sample to develop a feature around. I would say at least 5.

I've already approved the $70 for Lucy and time you spent with her. I'll be in contact with her about payment, and you can bill me whenever.

I want to wait on approving the other items until we have a clearer understanding of what we're testing for and why. We can talk about this on our next contributor call. I added this issue to our current milestone so it doesn't fall off the radar. Feel free to post any comments between now and our next meeting.

**Comment by bbertucc** [comment]
Assigning myself to this because it's in my court to improve until we get to something that can be budgeted.

**Comment by bbertucc** [comment]
One Note, while I'm thinking about it: Budget will probably come outside Equalify. There are a ton of grants that this project relates to. I think UCL might also be interested in supporting this. Here is a link to a bunch of grants: https://blog.thegrantportal.com/2024/07/29/grants-for-technology-driven-solutions-for-visual-impairment-challenges/

**Comment by kevinandrews1** [comment]
@bbertucc good points.
- The survey would be questions we send out to listserves like Educause and Athens. Depending on the responses the next step would be to follow up with certain individuals to participate in a user session.
    - That's $350 (5 one hour sessions at $70 each).
    - If you take two of the sessions I'll keep three and my consult budget doesn't  change.
- It would basically be a Google form and we'd be up front about for what we're using the data. we'd also have a question asking if they're ok being contacted for a followup. What do you think?

## Updated Budget
- Initial development: $X (tbd)
- Lucy's consultation: $70 (via Amazon or cash)
- Kevin's consultation: $555 (just under eight hours: an hour with Lucy on 12/16, an hour meeting tbd with @heythisischris and @azdak, a buffer of three hours for general UX/usability work, and up to three hours to meet with three others for guerilla UX to gather feedback)
- Comp up to five other people for their time and feedback: $350 ($70 per hour session, prioritizing disabled a11y pros/devs)
- Total so far: $975

I will bill for my regression testing on #502 #503 #504 #505 and #506 and my $70 for the hour consult with Lucy for Project Raga for now. That means there's a remaining $485 on this project to be paid out to me at a future date once we have more concrete plan and technical reqs. Does this all make sense?

Look forward to discussing more on our 12/23 call. Let me know if you have any thought sin the interim and I'll do likewise.

**Comment by bbertucc** [comment]
@kevinandrews1 and the team discussed this today. As per his discussion with Lucy, having a manual testing extension might not the be the best route. Instead, we should focus on how to automate tests that screen reader users rely on.
