### ISSUE TITLE
Make Scan Process Concurrent

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#61]
Currently, we send a URL to web services in a foreach loop. 

That means we have to wait to receive the output from the web service before we can add alerts.

To speed things up, we should send multiple URLs to the web service at once.

To do that, we would need to add `$integration_alerts($page)` function in an async loop.

The winner of this bounty must implement a concurrent process that sends multiple URLs to integrations without waiting for previous URLs to be processed.

Feel free to add third-party integrations like [AMP](https://amphp.org/amp/event-loop/api), which should be added via Composer.

You should not use added PHP extensions.

Please pull from the [mvp1.2-controller_scanning](https://github.com/bbertucc/equalify/tree/mvp1.2-controller_scanning) branch.

Winning solutions will be judged the solution's "readability" and performance. 

Winner gets $333 to a charity or PayPal/Venmo account of their choice.

Good luck!

**Comment by ebertucc** [comment]
Made a PR with the first pass at implementing this, along with an accompanying rewrite of the Little Forest integration. (Still need to rewrite the Wave integration.)

Introduces a Composer dependency on Guzzle and changes the API for integrations, which doesn't seem like too big a problem as only Little Forest and Wave have been written so far.

Questions/comments welcome.

**Comment by bbertucc** [comment]
You got the bounty @ebertucc !
