### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#68]
The average site has over 1000 accessibility errors. We would have to create some kind of a summary of errors. This is perhaps used in a "notifications" tab. That tab can select from weekly, daily, or monthly notifications.

Perhaps notifications are just handled in an integration? I could imagine users wanting different types of notification integrations. For instance, they could use sendgrid. Handling notifications and integrations would also free up the user interface. The only thing is that it could be less intuitive for users to have to click on an integration to update their notifications them to just click any notifications tab. 

If every user would want to notifications, why would it be an integration?

**Comment by kreynen** [comment]
Have you considered making email notifications a feature of reports?

My ideal solution would be to have more granularity at the alert level and be able to map issues types to labels like severity. Who gets an email would be a function of site + alert severity or site + alert number threshold.

The way Pantheon handles VRT thresholds is a great model for our use case. One Site Owner can decide that they are willing to accept a 10% difference in before/after images in Auto Pilot. Another Site Owner may want to know about even a 1% difference. For Equalify, one Site Owner might not add much new content and considers all of the existing reported issues acceptable. That users could configure a report to only send an email if the number of alerts was > 100.

**Comment by bbertucc** [comment]
This might be a "premium feature" added on the hosted version, since very few people who run Equalify locally will need email updates and email updates would require another service (ie- maybe we can have a mailgun integration?)

**Comment by bbertucc** [comment]
@mgifford had the great idea: 
> emails sent to people in each[ role](https://www.w3.org/WAI/EO/wiki/ARRM_Project_-_Accessibility_Roles_and_Responsibilities_Mapping) with issues related to them. Being able to customize this also helps.

**Comment by bbertucc** [comment]
We'll incorporate this on a hosted version.
