### ISSUE TITLE
Increase the 1,111 Page Limit

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#73]
In MVP 1.2 we limit users to 1,111 pages. 

We do that so we can guarantee Equalify works on our supported system.

Perhaps we need to increase that limit?

Very few early testers needed over 1,111 pages.

If you want more pages, add a 👍 to this thread or comment with your use case.

**Comment by bbertucc** [comment]
It's worth noting that Open Source users can increase the limit in `config.php`, but we only test up to 3,333 pages.

**Comment by jrchamp** [comment]
I think that covers most situations where users are manually creating pages/posts. Beyond a few hundred, it's likely to be programmatic content. However, anyone with a lot of data can quickly exceed that limit because it is common to programmatically generate pages based on data (such as 1000+ class offerings per semester).

**Comment by bbertucc** [comment]
Trimming the limit a bit more.. 3333 pages returned > 200k alerts for one site, which is currently hard to process on most machines. Hopefully, 1,111 will be enough pages for us to test our MVP. We should support more pages in the future to speak to the use case @jrchamp metioned.

**Comment by nsmsn** [comment]
I came in just over the limit on one of my sites, at 1,331 URLs (Jetpack-generated sitemap on WordPress site with posts going back to 2007)

**Comment by bbertucc** [comment]
Marking this for the next release. Targeting 2222 page limit.

**Comment by bbertucc** [comment]
In #112 @jenlampton reported:
> It would be nice if a scan could be completed in batches, so large-ish sites could also participate. 1,111 pages is nothing for a Drupal or Backdrop CMS website, and we need equalify too! (I would argue that large sites need this service even more than tiny sites, where people can realistically scan all pages manually.)

**Comment by bbertucc** [comment]
Added 1111 to the page limit. You can currently test with [mvp-4](https://github.com/bbertucc/equalify/tree/mvp-4) branch
