### ISSUE TITLE
Pagination logic creates unexpected results

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#79]
Currently, when five pages of alerts are shown, some pages are missing from the pagination:

<img width="293" alt="Screen Shot 2022-09-15 at 10 35 17 AM" src="https://user-images.githubusercontent.com/46652/190446398-2a1a931e-4c83-4d94-9edb-d02c4db23e4b.png">

My current pagination logic is currently terrible, so perhaps someone could refine my garbled logic? (Maybe for [hacktober](https://hacktoberfest.com/)?) 

All the pagination logic is here: https://github.com/bbertucc/equalify/blob/51e2b9d2d679326bfaf4285bcd7470d25b578dda/models/view_components.php#L206-L308

I aim to show no more than four page links and the current page.

Currently, if there are more than five pages, an ellipse appears.

Example 1:

<img width="396" alt="Screen Shot 2022-09-22 at 12 26 19 PM" src="https://user-images.githubusercontent.com/46652/191812677-882e04b8-726f-47f2-b485-9a1a732b44e1.png">

Example 2:

<img width="423" alt="Screen Shot 2022-09-22 at 12 27 46 PM" src="https://user-images.githubusercontent.com/46652/191812870-f04c9794-e01b-4446-88dd-d74a28b6be4d.png">

I'm not wed to this behavior, but we will need to account for giant lists of pages (some users have over 200 pages of alerts).

Curious to see your solutions!

**Comment by bbertucc** [comment]
My current pagination logic is currently terrible. This would be a great first issue for anyone, or perhaps an easy opportunity to get an 

All the logic is here: https://github.com/bbertucc/equalify/blob/51e2b9d2d679326bfaf4285bcd7470d25b578dda/models/view_components.php#L206-L308

The goal is to show no more than four page links and the current page at a time.

Currently, if there are more than five pages, an elipses appears.

Example 1:

<img width="396" alt="Screen Shot 2022-09-22 at 12 26 19 PM" src="https://user-images.githubusercontent.com/46652/191812677-882e04b8-726f-47f2-b485-9a1a732b44e1.png">

Example 2:

<img width="423" alt="Screen Shot 2022-09-22 at 12 27 46 PM" src="https://user-images.githubusercontent.com/46652/191812870-f04c9794-e01b-4446-88dd-d74a28b6be4d.png">

I'm not wed to this behavior, but we will need to giant lists of pages (some users have over 200 pages of alerts).

Curious to see your solutions!

**Comment by ellieya** [comment]
Can I work on this?

Edit: If yes, is there a way to quickly populate the alerts? I'm going to look through the documents for now but just in case you get back to me before I figure it out

Edit 2: I'm currently trying to do it via UI with the scan page, but the scan button is disabled and updateScanButton is running infinitely

**Comment by bbertucc** [comment]
Hey @ellieya - You can definitely jump on this! I don't know if anyone else is jumping on it too, but the more solutions means better code!

Note that if you want your submission to count toward Hacktober fest, you'll need to follow [Hacktober guidelines](https://hacktoberfest.com/participation/).

Here is SQL you can use to populate 5 alerts in your table:
```
INSERT INTO `alerts` (`status`, `type`, `source`, `site_id`, `url`, `message`, `archived`)
VALUES
	('active', 'error', 'test', 1, 'https://test.com', 'This is only a test', 1),
	('active', 'warning', 'test', 1, 'https://test.com', 'This is only a test', 1),
	('active', 'error', 'test', 1, 'https://test.com', 'This is only a test', 1),
	('active', 'error', 'test', 1, 'https://test.com', 'This is only a test', 1),
	('active', 'warning', 'test', 1, 'https://test.com', 'This is only a test', 1);
```
You can run that SQL multiple times to add many alerts, but **remember to delete the SQL!!** Since the alerts are not tied to existing sites, they'll cause issues if you don't delete them.

I responded to your question about the disabled button in #94.

**Comment by bbertucc** [comment]
To quickly test your work, I suggest adding "testing" values to the variables in https://github.com/bbertucc/equalify/blob/dbe6db045f2a09e39629eb3d77e95083fde0c621/models/view_components.php#L206

Here is a demo gist: https://gist.github.com/bbertucc/cdb72b0b384c8ea347f9f0eb1989af86

I'm using these testing values:
```
    $current_page_number = 4;
    $item_number = 4;
    $total_pages = 7;
    $view_parameters = '';
```

I've also commented out select functions, noted by "TESTING" in the markup.

**Comment by ellieya** [comment]
@bbertucc I am so sorry for the delays; I actually finished off the logic 2 weeks ago but personal life got in the way so my hands were tied for a while.

Pull request is here: https://github.com/bbertucc/equalify/pull/105#issue-1402782831

Let me know what you think; I do have an idea for a more compact version if you would like more ideas but I wanted to make sure I was following the correct coding conventions first.

Also, while working on it, I found a bug where if you tried clicking on any pagination link other than 1 or max page when arriving to alerts via homepage, it would result in error. I don't think the fix should be too hard if you don't mind me working on it. (The workaround I currently use is just to click on Alerts before testing the pagination logic)

**Comment by bbertucc** [comment]
Amazing @ellieya! My wedding is this week, so I might be a bit delayed in reviewing but I will review ASAP. Thanks again! You rock!

**Comment by bbertucc** [comment]
Change Management-based A11Y reporting

**Comment by bbertucc** [comment]
Closing this for #105
