### ISSUE TITLE
Allow for XML sitemap index files

### ISSUE THREAD

**Issue by thatdevgirl** [bbertucc/equalify#82]
Many of our sites are WordPress sites that use the Yoast SEO plugin, which auto-generates XML files. Yoast creates a sitemap index XML file, which contains a number of child XML files - e.g. one for all pages, several for all posts _(it seems to break up the posts into multiple XML files - we have a lot of posts)_.

If I want to scan one of these sites by XML, I cannot use the index file. I need to use one of the child XML files.

For example, this will not scan: https://www.georgetown.edu/sitemap_index.xml

However, this will: https://www.georgetown.edu/page-sitemap.xml

Probably not a big deal, because I can scan the pages and posts of a site individually, but it would be nice to be able to scan both sets of pages together.

(I do know that I can use the WordPress option to scan the site, but we have far more than 100 pages on many of these sites.)

**Comment by bbertucc** [comment]
Several folks use Yoast so this is a priority enhancement.

I'm tagging it for our next release.

Thanks @thatdevgirl!

**Comment by bbertucc** [comment]
I'm moving this out of MVP-4 milestone, since that release is more about reporting than XML. I'll push for a release around XML.

**Comment by bbertucc** [comment]
With #198, Equalify can handle this with a third-party scanning service.
