### ISSUE TITLE
WAVE error: "Not enough credits"

### ISSUE THREAD

**Issue by thatdevgirl** [bbertucc/equalify#83]
I am getting an error - `WAVE error:"Not enough credits."`, when scanning sites. I have tried to scan:

* Georgetown's main site via XML at https://www.georgetown.edu/page-sitemap.xml
* My personal website as a single page at https://jhalabi.com

<img width="715" alt="Screen Shot 2022-09-19 at 10 39 52 PM" src="https://user-images.githubusercontent.com/5687778/191155503-cc89cb2b-d74b-43a5-ba2e-9c27c744801e.png">

Did I hit some API limit?

**Comment by bbertucc** [comment]
All fixed!

We had so many fantastic users that I needed to up our WAVE credits.

Thanks for the bug report!
