### ISSUE TITLE
Sites interface improvement ideas

### ISSUE THREAD

**Issue by thatdevgirl** [bbertucc/equalify#84]
A couple of suggestions for improving the "[All Sites](https://service.equalify.app/index.php?view=sites)" page. (Low priority)

1. Allow a site to be edited. Right now, once I add a site, I cannot update it if I made an error in entering the URL.
2. Allow a site to be removed.
3. Allow a site to have a name. The sites are all labelled by either URL or sitemap XML path, which can be hard to read.

**Comment by bbertucc** [comment]
Closing this issue. We'll be revamping the way sites are added with #204.
