### ISSUE TITLE
Improve WAVE key error message

### ISSUE THREAD

**Issue by kreynen** [bbertucc/equalify#85]
I'm completely new to this project so I was trying to follow along with https://github.com/bbertucc/equalify#download-and-use to spin it up and take a look. I'm configuring this within https://ddev.com/. The db settings I'd need in the config.php are straightforward, but I didn't know what a WAVE key was so I left that blank.

The lack of a WAVE Key is caught in https://github.com/bbertucc/equalify/blob/main/install.php#L12, but with `Fatal error: Uncaught Exception: WAVE key is missing from config.php`. https://www.google.com/search?q=google+wave+key didn't return anything useful.

I was eventually able to figure out I needed to register for an account at https://wave.webaim.org/api/.

It would have saved me some time if instead of just telling me the `WAVE key is missing`, the error pointed users to https://wave.webaim.org/api/ or the need for a WAVE Key was added to https://github.com/bbertucc/equalify#download-and-use  and the error linked to that.

Happy to submit a PR for either improvement.

**Comment by bbertucc** [comment]
This is a great enhancement! A PR would be much appreciated. Here is where the error text comes from: https://github.com/bbertucc/equalify/blob/51e2b9d2d679326bfaf4285bcd7470d25b578dda/install.php#L12

**Comment by bbertucc** [comment]
Updated the error message to `Equalify requires a WAVE key. Get your key at https://wave.webaim.org/api/ and add it to the config.php file.` Will be released with [MVP-4](https://github.com/bbertucc/equalify/tree/mvp-4).
