### ISSUE TITLE
per_page and $GLOBALS['page_limit'] have to match

### ISSUE THREAD

**Issue by kgrimley-bu** [bbertucc/equalify#87]
When pointing to a WP site the `per_page` param is set to 100 you have to set `$GLOBALS['page_limit']` to 100 or you get an error. Say for instance you wanted to limit the scan to 10 pages you get the following...
```
Begin scan on 21/09/2022 at 01:57:07.


> Processing sites...
- https://www.butler.edu
> Found 100 scannable pages.

|=========================================|
|               SCAN STOPPED              |
|=========================================|

You have too many pages.

Equalify allows up to 10 pages.

Archive sites or delete pages from WordPress/XML.
```

It seems like one should be an upper limit and the other the actual count. So it's more like, give me x number of pages but don't exceed y number.

**Comment by bbertucc** [comment]
`$GLOBALS['page_limit']` is actually the limit for the scan, not the WordPress page adder. 

WordPress sets the 100 WP page limit. See [WP API Pagination parameters](https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/#pagination-parameters) and #90 .

That said, I'm going to keep this issue open. We need to add more descriptive text to explain what `$GLOBALS['page_limit']` actually limits. We also probably need to update the instructional text on the WP adder to say "The WordPress API limits imports to 100 records."

**Comment by bbertucc** [comment]
Side note: anyone anyone can get past that 100 record limit by using the XML importer instead of the WP importer.

**Comment by kgrimley-bu** [comment]
Get what you're saying. I guess my confusion and why I dropped it here is that it seems like if you set the `$GLOBALS['page_limit']` to less than what is returned by the call it's shouldn't error out. Hope that makes sense

**Comment by bbertucc** [comment]
> if you set the `$GLOBALS['page_limit']` to less than what is returned by the call it's shouldn't error out.

Makes total sense! Tagging this as something to fix next release.

**Comment by bbertucc** [comment]
MVP 4 should now resolve this.
