### ISSUE TITLE
Why is the "Run Scan" button always disabled?

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#94]
In #79, @ellieya reported that that the "Run Scan" button is disabled.

**Comment by bbertucc** [comment]
The "Run Scan" button is disabled if `scan_status` in the database is set to "running".

https://github.com/bbertucc/equalify/blob/dbe6db045f2a09e39629eb3d77e95083fde0c621/views/scan.php#L169

To resolve this issue, first ensure a scan isn't running by looking at your server processes or restarting your server.

If a scan isn't running, remove the "running" `meta_value` from the database `meta` table to reset the status.

Here is the MySQL that you can run:
```
UPDATE `meta` SET `meta_value` = "" WHERE `meta_name` = "scan_status"
```

Does that resolve your issue @ellieya?

**Comment by ellieya** [comment]
@bbertucc Yes, the scan button is no longer disabled when I ran this in MySQL
<code>UPDATE \`meta\` SET \`meta_value\` = "" WHERE \`meta_name\` = "scan_status"</code>
But even when I click 'Run Scan' after the value has been reset, the scan doesn't appear to be running. (Console says "No scan is running.")

I don't know if it matters, but I have the following sites added:
![image](https://user-images.githubusercontent.com/26253049/192330281-431e535e-4baa-4f08-ad94-85e84f30908a.png)

**Comment by bbertucc** [comment]
> But even when I click 'Run Scan' after the value has been reset, the scan doesn't appear to be running. (Console says "No scan is running.")

@ellieya - Are you running the [latest version](https://github.com/bbertucc/equalify/releases/tag/MVP-3-1)? Are you running version 8.1 of PHP? Do you have all the proper settings in your `config.php` file?https://github.com/bbertucc/equalify/blob/dbe6db045f2a09e39629eb3d77e95083fde0c621/sample-config.php#L12-L21

**Comment by ellieya** [comment]
@bbertucc Sorry for the late response, life kinda got in the way.

Yes, I have PHP 8.1.6 installed and my config.php is set up like this (I don't have a password on MySQL)

```
// Configure database.
$GLOBALS['DB_HOST'] = 'localhost';
$GLOBALS['DB_USERNAME'] = 'root';
$GLOBALS['DB_PASSWORD'] = '';
$GLOBALS['DB_NAME'] = 'equalify';
$GLOBALS['DB_PORT'] = '3306';
$GLOBALS['DB_SOCKET'] = '/tmp/mysql/mysql.sock';

// Configure PHP path, which you can find by running 
// `which php` in a terminal.
$GLOBALS['PHP_PATH'] = '/usr/local/bin/php';

// Scanner settings.
$GLOBALS['wave_key'] = '[redacted]';

// Additional options.
$GLOBALS['page_limit'] = '1111';
$GLOBALS['scan_concurrency'] = '6';
$GLOBALS['scan_timeout'] = '33';
```

Is it possible that it's because I'm on Windows?

**Comment by bbertucc** [comment]
@ellieya - Sounds like there might be a configuration issue with your local environment. Some folks have luck with [ddev](https://ddev.com/). Checkout this comment: https://github.com/bbertucc/equalify/issues/40#issuecomment-1252955640

If that doesn't work, I'm adding another workaround to #79

**Comment by ellieya** [comment]
@bbertucc I'll try it out. If I have any success, I'll try to start tackling some of the scan-related bugs.

Edit: I have Docker and DDEV set up according to how [kreynen](https://github.com/kreynen) had it set up on https://github.com/bbertucc/equalify/issues/40#issuecomment-1256343020

Unfortunately, no luck... I'll try using another computer next week.

**Comment by bbertucc** [comment]
Closing this issue, since we can't recreate the errors. Happy to re-open it if needed.
