### ISSUE TITLE
Allow Sitemap.xml to be limited by total items and patterns

### ISSUE THREAD

**Issue by kreynen** [bbertucc/equalify#99]
Related to https://github.com/bbertucc/equalify/issues/82, but basically the opposite.

Rather than follow the main sitemap.xml file to sub sitemap.xml files, I would like to be able to limit the crawl by a few things:

- [ ] Total number of items - This would be useful for testing. I burned through 100 WAVE credits by using a site with 200 pages in the sitemap.xml to test against. It would be helpful to have an Advanced option to limit the scan to the first 10 URLs in the XML.
- [ ] Sitemap Priority - Only scan items with Priority > .7
- [ ] URL Patterns - Regex FTW!

**Comment by bbertucc** [comment]
Equalify is focusing on issue management (see #198). This issue should therefore be dealt with by a third-party scanning service, like https://github.com/dequelabs/axe-core/. You can also check out an experimental scanning service that we are building: https://github.com/EqualifyApp/scan
